-- Create Toy Listing Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0003_create_toy_listing_tables.sql
-- Description: Creates toys, toy_photos, and toy_views tables with ENUMs, constraints, indexes, and RLS support
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Condition enum for toy state/quality (like_new, good, fair, poor)
CREATE TYPE public.condition_enum AS ENUM (
  'like_new',  -- Toy appears brand new, unused or barely used
  'good',      -- Toy is in good condition with minimal wear
  'fair',      -- Toy has visible wear but is fully functional
  'poor'       -- Toy has significant wear or minor damage but is still usable
);

-- Toy status enum for lifecycle management and soft delete
CREATE TYPE public.toy_status_enum AS ENUM (
  'pending_moderation',  -- Toy submitted but awaiting admin approval
  'active',              -- Toy is active and visible to other users
  'unavailable',         -- Toy is temporarily unavailable (in an active exchange)
  'delisted'             -- Toy has been soft-deleted by user or admin
);

-- ============================================================================
-- TOYS TABLE
-- ============================================================================
-- Stores toy listings created by users
-- Core table for the ticket economy's primary asset
-- Uses denormalized photos_count for query performance

CREATE TABLE IF NOT EXISTS public.toys (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  category VARCHAR(50) NOT NULL,
  tags TEXT[] DEFAULT NULL,
  age_range TEXT[] DEFAULT NULL,
  condition public.condition_enum NOT NULL,
  status public.toy_status_enum NOT NULL DEFAULT 'pending_moderation',
  photos_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  moderation_notes TEXT DEFAULT NULL,

  -- Constraints
  CONSTRAINT valid_condition CHECK (condition IN ('like_new', 'good', 'fair', 'poor')),
  CONSTRAINT valid_status CHECK (status IN ('pending_moderation', 'active', 'unavailable', 'delisted')),
  CONSTRAINT valid_photos_count CHECK (photos_count >= 0),
  CONSTRAINT valid_name CHECK (name <> ''),
  CONSTRAINT valid_category CHECK (category <> '')
);

-- Add comments for documentation
COMMENT ON TABLE public.toys IS 'User toy listings - core asset in the ticket economy system';
COMMENT ON COLUMN public.toys.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.toys.user_id IS 'UUID foreign key to profiles.id - toy lister';
COMMENT ON COLUMN public.toys.name IS 'Toy name/title (required, non-empty TEXT)';
COMMENT ON COLUMN public.toys.description IS 'Detailed toy description (optional TEXT)';
COMMENT ON COLUMN public.toys.category IS 'Category classification (toys, books, games, sports, educational, etc.)';
COMMENT ON COLUMN public.toys.tags IS 'Array of searchable tags (e.g., [''LEGO'', ''building'', ''ages 5+''])';
COMMENT ON COLUMN public.toys.age_range IS 'Array of suitable age groups (e.g., [''4-7'', ''8-12''])';
COMMENT ON COLUMN public.toys.condition IS 'Toy condition ENUM (like_new, good, fair, poor)';
COMMENT ON COLUMN public.toys.status IS 'Soft delete status ENUM (pending_moderation, active, unavailable, delisted)';
COMMENT ON COLUMN public.toys.photos_count IS 'Denormalized count of photos in toy_photos (cached for query perf)';
COMMENT ON COLUMN public.toys.created_at IS 'Timestamp when toy was listed';
COMMENT ON COLUMN public.toys.updated_at IS 'Timestamp when toy was last updated';
COMMENT ON COLUMN public.toys.moderation_notes IS 'Admin notes from moderation process (optional TEXT)';

-- ============================================================================
-- TOY_PHOTOS TABLE
-- ============================================================================
-- Stores metadata for toy photos stored in Supabase Storage
-- Photos themselves are stored in Supabase Storage, not as BLOBs in database
-- Maintains ordering for gallery display

CREATE TABLE IF NOT EXISTS public.toy_photos (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  toy_id UUID NOT NULL REFERENCES public.toys(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL,
  display_order INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_storage_path CHECK (storage_path <> ''),
  CONSTRAINT valid_display_order CHECK (display_order >= 1)
);

-- Add comments for documentation
COMMENT ON TABLE public.toy_photos IS 'Photo metadata for toy listings (actual images stored in Supabase Storage)';
COMMENT ON COLUMN public.toy_photos.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.toy_photos.toy_id IS 'UUID foreign key to toys.id (CASCADE DELETE)';
COMMENT ON COLUMN public.toy_photos.storage_path IS 'Supabase Storage path to the image file';
COMMENT ON COLUMN public.toy_photos.display_order IS 'Order for gallery display (1, 2, 3, ...)';
COMMENT ON COLUMN public.toy_photos.created_at IS 'Timestamp when photo was uploaded';

-- ============================================================================
-- TOY_VIEWS TABLE
-- ============================================================================
-- Stores toy view analytics for engagement tracking
-- Tracks both authenticated users and anonymous viewers
-- Used for popularity metrics and recommendation algorithms

CREATE TABLE IF NOT EXISTS public.toy_views (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  toy_id UUID NOT NULL REFERENCES public.toys(id) ON DELETE CASCADE,
  viewer_user_id UUID DEFAULT NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add comments for documentation
COMMENT ON TABLE public.toy_views IS 'Toy view analytics for engagement tracking and recommendations';
COMMENT ON COLUMN public.toy_views.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.toy_views.toy_id IS 'UUID foreign key to toys.id (CASCADE DELETE)';
COMMENT ON COLUMN public.toy_views.viewer_user_id IS 'UUID foreign key to profiles.id (nullable for anonymous views, SET NULL on delete)';
COMMENT ON COLUMN public.toy_views.viewed_at IS 'Timestamp when toy was viewed';

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Strategic indexes for common query patterns and performance optimization
-- These indexes support the most frequent queries without creating excessive write overhead

-- Toys table indexes
-- Index on toys.user_id for efficient lookups of toys by user (lister)
CREATE INDEX IF NOT EXISTS idx_toys_user_id ON public.toys(user_id);

-- Index on toys.status for efficient soft delete queries (WHERE status = 'active')
CREATE INDEX IF NOT EXISTS idx_toys_status ON public.toys(status);

-- Index on toys.category for efficient category browsing
CREATE INDEX IF NOT EXISTS idx_toys_category ON public.toys(category);

-- GIN index on toys.tags for fast array searches (e.g., WHERE 'LEGO' = ANY(tags))
CREATE INDEX IF NOT EXISTS idx_toys_tags_gin ON public.toys USING GIN(tags);

-- Index on toys.created_at for sorting by newest listings
CREATE INDEX IF NOT EXISTS idx_toys_created_at ON public.toys(created_at DESC);

-- Composite index for common query pattern: user's active toys
CREATE INDEX IF NOT EXISTS idx_toys_user_status ON public.toys(user_id, status);

-- Toy_photos table indexes
-- Index on toy_photos.toy_id for efficient photo lookups by toy
CREATE INDEX IF NOT EXISTS idx_toy_photos_toy_id ON public.toy_photos(toy_id);

-- Index on toy_photos.display_order for gallery ordering
CREATE INDEX IF NOT EXISTS idx_toy_photos_display_order ON public.toy_photos(toy_id, display_order);

-- Toy_views table indexes
-- Index on toy_views.toy_id for view count queries and analytics
CREATE INDEX IF NOT EXISTS idx_toy_views_toy_id ON public.toy_views(toy_id);

-- Index on toy_views.viewed_at for time-based analytics and trending
CREATE INDEX IF NOT EXISTS idx_toy_views_viewed_at ON public.toy_views(viewed_at DESC);

-- Index on toy_views.viewer_user_id for user view history
CREATE INDEX IF NOT EXISTS idx_toy_views_viewer_user_id ON public.toy_views(viewer_user_id);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on all three tables for user data isolation
-- Specific policies will be created in a separate RLS policies migration

ALTER TABLE public.toys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toy_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.toy_views ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Notes:
-- ============================================================================
-- 1. RLS policies are NOT created in this migration. They will be added separately in:
--    supabase/migrations/rls_policies.sql
--
-- 2. Soft delete via status column:
--    - status = 'pending_moderation': Toy submitted but awaiting admin approval
--    - status = 'active': Toy visible to other users for exchange
--    - status = 'unavailable': Toy currently in an active exchange
--    - status = 'delisted': Toy soft-deleted by user or admin
--    - RLS policies and API layer should filter out 'delisted' toys from queries
--
-- 3. Denormalized photos_count:
--    - The photos_count column in toys table is denormalized for query performance
--    - Avoids expensive COUNT queries when fetching toy listings
--    - Application layer or triggers should keep this in sync with toy_photos table
--    - Consider using PostgreSQL trigger for automatic synchronization
--
-- 4. Photos stored in Supabase Storage:
--    - Images are NOT stored as BLOBs in the database
--    - Only storage paths are stored in toy_photos.storage_path
--    - This follows Supabase best practices for scalable media storage
--    - Supabase Storage has built-in RLS policies for secure access
--
-- 5. Toy_views for analytics:
--    - Tracks both authenticated and anonymous views
--    - viewer_user_id is nullable for anonymous/unauthenticated viewers
--    - Used for popularity metrics, trending recommendations, and engagement analysis
--    - High write volume table; consider archiving old views to improve performance
--
-- 6. Tag searches with GIN index:
--    - GIN index on tags enables fast array searches
--    - Query pattern: SELECT * FROM toys WHERE tags @> ARRAY['LEGO']::text[]
--    - GIN indexing is more efficient than BTREE for array searches
--
-- 7. Indexes are strategic for common patterns:
--    - idx_toys_user_id: Support "get my listings"
--    - idx_toys_status: Support "show active toys only"
--    - idx_toys_category: Support category browsing
--    - idx_toys_tags_gin: Support tag-based search
--    - idx_toys_created_at: Support "newest first" sorting
--    - idx_toys_user_status: Composite for "user's active toys"
--    - idx_toy_photos_toy_id: Support "get photos for toy"
--    - idx_toy_views_toy_id: Support "view count" analytics
--    - idx_toy_views_viewed_at: Support "trending" queries
--
-- 8. Foreign key constraints:
--    - toys -> profiles: ON DELETE CASCADE (if user deleted, toys deleted)
--    - toy_photos -> toys: ON DELETE CASCADE (if toy deleted, photos deleted)
--    - toy_views -> profiles: ON DELETE SET NULL (if viewer deleted, keep view record)
--    - toy_views -> toys: ON DELETE CASCADE (if toy deleted, views deleted)
--
-- 9. ENUM type usage:
--    - condition_enum ensures only valid toy conditions are stored
--    - toy_status_enum enforces strict status transitions
--    - CHECK constraints provide additional validation
--
-- 10. Array column usage:
--     - tags and age_range use PostgreSQL's native TEXT[] array type
--     - JSON arrays are NOT used for better performance and simpler querying
--     - Queryable with: 'value' = ANY(tags) or tags @> ARRAY['value']::text[]
