-- Fix Profiles Table Auth Dependency
-- Migration: 20241114_0007_fix_profiles_auth_dependency.sql
-- Description: Remove hard dependency on auth.users to allow testing and direct profile creation

-- Step 1: Drop dependent views and indexes
DROP INDEX IF EXISTS public.idx_profiles_email CASCADE;
DROP VIEW IF EXISTS public.user_age_groups CASCADE;

-- Step 2: Drop and recreate the profiles table without auth.users dependency
-- Drop the old foreign key first
ALTER TABLE public.kids DROP CONSTRAINT IF EXISTS "kids_parent_id_fkey";
DROP TABLE IF EXISTS public.profiles CASCADE;

-- Step 3: Recreate profiles table with UUID primary key (no auth.users reference)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  language VARCHAR(2) DEFAULT 'en' NOT NULL,
  notification_preference JSONB DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Step 4: Recreate indexes
CREATE INDEX idx_profiles_email ON public.profiles(email);

-- Step 5: Recreate kids table with proper foreign key constraint
CREATE TABLE public.kids (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  parent_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  birthdate DATE,
  age_group public.age_group_enum GENERATED ALWAYS AS (
    CASE
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 3 THEN '0-2'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 6 THEN '3-5'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 9 THEN '6-8'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 12 THEN '9-11'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 15 THEN '12-14'::public.age_group_enum
      ELSE '15+'::public.age_group_enum
    END
  ) STORED,
  interests TEXT[] DEFAULT ARRAY[]::TEXT[],
  allergies TEXT,
  status public.kid_status_enum DEFAULT 'active' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_age_group CHECK (age_group IN ('0-2', '3-5', '6-8', '9-11', '12-14', '15+')),
  CONSTRAINT valid_status CHECK (status IN ('active', 'hidden', 'deleted')),
  CONSTRAINT valid_birthdate CHECK (birthdate <= CURRENT_DATE)
);

-- Step 6: Recreate indexes on kids table
CREATE INDEX idx_kids_parent_id ON public.kids(parent_id);
CREATE INDEX idx_kids_status ON public.kids(status);
CREATE INDEX idx_kids_parent_status ON public.kids(parent_id, status);

-- Step 7: Recreate user_age_groups view
CREATE OR REPLACE VIEW public.user_age_groups AS
SELECT
  k.parent_id,
  k.age_group,
  COUNT(k.id) AS child_count,
  ARRAY_AGG(k.id) FILTER (WHERE k.status = 'active') AS active_child_ids,
  COUNT(k.id) FILTER (WHERE k.status = 'active') AS active_count,
  COUNT(k.id) FILTER (WHERE k.status = 'hidden') AS hidden_count,
  COUNT(k.id) FILTER (WHERE k.status = 'deleted') AS deleted_count,
  MAX(k.updated_at) AS last_updated
FROM public.kids k
GROUP BY k.parent_id, k.age_group;

-- Step 8: Re-enable RLS on both tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kids ENABLE ROW LEVEL SECURITY;
ALTER VIEW public.user_age_groups SET (security_barrier = on);

-- Step 9: Add documentation comments
COMMENT ON TABLE public.profiles IS 'Parent/guardian user profiles (independent from auth)';
COMMENT ON COLUMN public.profiles.id IS 'UUID primary key, auto-generated';
COMMENT ON COLUMN public.profiles.email IS 'Unique email address for the parent/guardian';
COMMENT ON COLUMN public.profiles.full_name IS 'Full name of the parent/guardian';
COMMENT ON COLUMN public.profiles.language IS 'User language preference (ISO 639-1 code, default: en)';
COMMENT ON COLUMN public.profiles.notification_preference IS 'JSONB storing user notification preferences';
COMMENT ON COLUMN public.profiles.created_at IS 'Timestamp when profile was created';
COMMENT ON COLUMN public.profiles.updated_at IS 'Timestamp when profile was last updated';

COMMENT ON TABLE public.kids IS 'Child/dependent profiles owned by parent/guardian (profiles)';
COMMENT ON COLUMN public.kids.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.kids.parent_id IS 'UUID foreign key to profiles.id';
COMMENT ON COLUMN public.kids.name IS 'Child name';
COMMENT ON COLUMN public.kids.birthdate IS 'Child birthdate (DATE format)';
COMMENT ON COLUMN public.kids.age_group IS 'Computed age group (0-2, 3-5, 6-8, 9-11, 12-14, 15+) from birthdate';
COMMENT ON COLUMN public.kids.interests IS 'Array of interest tags (e.g., ARRAY[''sports'', ''art''])';
COMMENT ON COLUMN public.kids.allergies IS 'Optional allergy information';
COMMENT ON COLUMN public.kids.status IS 'Soft delete status (active, hidden, deleted)';
COMMENT ON COLUMN public.kids.created_at IS 'Timestamp when record was created';
COMMENT ON COLUMN public.kids.updated_at IS 'Timestamp when record was last updated';

COMMENT ON VIEW public.user_age_groups IS 'Aggregated view of kids grouped by age_group per parent_id';
