-- Create Parental Consent Records Table for GDPR Compliance
-- Migration: 20241114_0017_create_consent_records.sql
-- Description: Creates consent_records table for audit trail of parental consents (child_data, marketing).
--              Also adds consent_status column to kids table for state tracking.
--              Includes RLS policies restricting access to users, admins, and service role.
--              Implements immutable audit trail (no UPDATE allowed).

-- ============================================================================
-- 1. CONSENT_RECORDS TABLE
-- ============================================================================
-- Stores audit trail of all parental consents with IP and user agent for GDPR compliance
-- Supports consent revocation via revoked_at (soft delete, not hard delete)
-- child_ids is UUID array containing consented child UUIDs (empty for marketing consents)

CREATE TABLE IF NOT EXISTS public.consent_records (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  consent_type VARCHAR(50) NOT NULL,
  child_ids UUID[] DEFAULT '{}',
  consent_text TEXT NOT NULL,
  ip_address INET,
  user_agent TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP WITH TIME ZONE,

  -- Constraints
  CONSTRAINT consent_type_valid CHECK (consent_type IN ('child_data', 'marketing')),
  CONSTRAINT timestamp_not_future CHECK (timestamp <= CURRENT_TIMESTAMP),
  CONSTRAINT revoked_after_granted CHECK (revoked_at IS NULL OR revoked_at >= timestamp)
);

-- Add documentation
COMMENT ON TABLE public.consent_records IS
'Audit trail for parental consents. Records every consent given (child_data, marketing).
Supports consent revocation (soft delete via revoked_at).
child_ids array stores UUID of children for whom consent was given.
IP and user agent logged for fraud investigation and GDPR audit purposes.
Immutable after creation (no UPDATE allowed).';

COMMENT ON COLUMN public.consent_records.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.consent_records.user_id IS 'UUID foreign key to profiles.id (parent/guardian)';
COMMENT ON COLUMN public.consent_records.consent_type IS 'Type of consent: child_data or marketing';
COMMENT ON COLUMN public.consent_records.child_ids IS
'Array of child UUIDs for whom consent was given.
Empty array for marketing consents.
Used to track which specific children user consented to data collection for.';
COMMENT ON COLUMN public.consent_records.consent_text IS
'Exact text shown to user at time of consent (versioning).
Preserved for audit trail and legal disputes.';
COMMENT ON COLUMN public.consent_records.ip_address IS 'Client IP address (INET type) from request';
COMMENT ON COLUMN public.consent_records.user_agent IS 'Client user agent string (browser or mobile client)';
COMMENT ON COLUMN public.consent_records.timestamp IS
'When consent was given (defaults to now(), cannot be in future).
Immutable - set at creation time.';
COMMENT ON COLUMN public.consent_records.revoked_at IS
'When consent was revoked (if applicable). NULL means consent still active.
Must be >= timestamp (cannot revoke before giving consent).';

-- ============================================================================
-- 2. CONSENT_RECORDS INDEXES
-- ============================================================================
-- Strategic indexes for efficient consent queries and GDPR auditing

CREATE INDEX IF NOT EXISTS idx_consent_records_user_id ON public.consent_records(user_id);
COMMENT ON INDEX idx_consent_records_user_id IS
'Lookup all consents for user. Primary access pattern.
Used for: SELECT * FROM consent_records WHERE user_id = X';

CREATE INDEX IF NOT EXISTS idx_consent_records_consent_type ON public.consent_records(consent_type);
COMMENT ON INDEX idx_consent_records_consent_type IS
'Filter consents by type (child_data vs marketing).
Used for: SELECT * FROM consent_records WHERE consent_type = ''child_data''';

CREATE INDEX IF NOT EXISTS idx_consent_records_timestamp_desc ON public.consent_records(timestamp DESC);
COMMENT ON INDEX idx_consent_records_timestamp_desc IS
'Recent consents first (audit trail).
Used for: SELECT * FROM consent_records WHERE timestamp > X ORDER BY timestamp DESC';

CREATE INDEX IF NOT EXISTS idx_consent_records_child_ids ON public.consent_records USING GIN(child_ids);
COMMENT ON INDEX idx_consent_records_child_ids IS
'Array containment queries (find consents by child).
Used for: SELECT * FROM consent_records WHERE child_id = ANY(child_ids)';

CREATE INDEX IF NOT EXISTS idx_consent_records_user_timestamp ON public.consent_records(user_id, timestamp DESC);
COMMENT ON INDEX idx_consent_records_user_timestamp IS
'User consent history (composite index).
Used for: SELECT * FROM consent_records WHERE user_id = X ORDER BY timestamp DESC';

CREATE INDEX IF NOT EXISTS idx_consent_records_revoked_at ON public.consent_records(revoked_at)
WHERE revoked_at IS NOT NULL;
COMMENT ON INDEX idx_consent_records_revoked_at IS
'Partial index for revoked consents only (small subset).
Used for: SELECT * FROM consent_records WHERE revoked_at IS NOT NULL';

-- ============================================================================
-- 3. UPDATE KIDS TABLE - ADD CONSENT_STATUS COLUMN
-- ============================================================================
-- Tracks parental consent state for each child
-- States: pending_consent (waiting), consented (active), consent_revoked (parent revoked),
--         scheduled_for_deletion (grace period active)

ALTER TABLE IF EXISTS public.kids
ADD COLUMN IF NOT EXISTS consent_status VARCHAR(20) DEFAULT 'pending_consent' NOT NULL
CHECK (consent_status IN ('pending_consent', 'consented', 'consent_revoked', 'scheduled_for_deletion'));

COMMENT ON COLUMN public.kids.consent_status IS
'Tracks parental consent state: pending_consent (waiting), consented (active),
consent_revoked (parent revoked), scheduled_for_deletion (grace period active).
Used to enforce GDPR compliance - child data cannot be processed without consent.';

-- Index on consent_status for efficient filtering
CREATE INDEX IF NOT EXISTS idx_kids_consent_status ON public.kids(consent_status);
COMMENT ON INDEX idx_kids_consent_status IS
'Filter kids by consent status. Used for: SELECT * FROM kids WHERE consent_status = ''consented''';

-- Composite index for common query: active children with consent
CREATE INDEX IF NOT EXISTS idx_kids_parent_consent ON public.kids(parent_id, consent_status);
COMMENT ON INDEX idx_kids_parent_consent IS
'Find all consented children for a parent. Used for: SELECT * FROM kids
WHERE parent_id = X AND consent_status = ''consented''';

-- ============================================================================
-- 4. ROW-LEVEL SECURITY (RLS) - CONSENT_RECORDS TABLE
-- ============================================================================
-- Enable RLS on consent_records
ALTER TABLE IF EXISTS public.consent_records ENABLE ROW LEVEL SECURITY;

-- Policy: Users can SELECT their own consent records
CREATE POLICY IF NOT EXISTS consent_records_select_own ON public.consent_records
  AS PERMISSIVE
  FOR SELECT
  USING (user_id = auth.uid());

COMMENT ON POLICY consent_records_select_own ON public.consent_records IS
'GDPR: Users can view their own consent records. Supports transparency and audit rights.';

-- Policy: Admins can SELECT all consent records (for audit and moderation)
CREATE POLICY IF NOT EXISTS consent_records_select_admin ON public.consent_records
  AS PERMISSIVE
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE user_id = auth.uid() AND is_active = true
    )
  );

COMMENT ON POLICY consent_records_select_admin ON public.consent_records IS
'Admins can view all consent records for compliance auditing and dispute resolution.
Checks admin_users table for verification (is_active = true).';

-- Policy: Only service role can INSERT (API/Edge Function only)
CREATE POLICY IF NOT EXISTS consent_records_insert_service ON public.consent_records
  AS PERMISSIVE
  FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

COMMENT ON POLICY consent_records_insert_service ON public.consent_records IS
'CRITICAL: Only Supabase service role can INSERT consent records.
Prevents clients from creating forged consent records.
API layer must call with service_role key (never client-side).';

-- Policy: No UPDATE allowed (immutable audit trail)
CREATE POLICY IF NOT EXISTS consent_records_no_update ON public.consent_records
  AS RESTRICTIVE
  FOR UPDATE
  WITH CHECK (false);

COMMENT ON POLICY consent_records_no_update ON public.consent_records IS
'Immutable audit trail: no UPDATE allowed on consent records.
Only INSERT and soft DELETE (revoked_at) permitted.';

-- Policy: Only service role can DELETE (long-term data purge after GDPR request)
CREATE POLICY IF NOT EXISTS consent_records_delete_service ON public.consent_records
  AS PERMISSIVE
  FOR DELETE
  USING (auth.role() = 'service_role');

COMMENT ON POLICY consent_records_delete_service ON public.consent_records IS
'Only service role can DELETE consent records (for GDPR data purge workflows).
User cannot delete own consent records (immutable audit trail).';

-- ============================================================================
-- 5. HELPER FUNCTIONS FOR CONSENT MANAGEMENT
-- ============================================================================

-- Function: get_child_consent_status
-- Returns: consent status, has_consent boolean, consent_record_id, consented_at timestamp
CREATE OR REPLACE FUNCTION public.get_child_consent_status(p_child_id UUID)
RETURNS TABLE(
  status VARCHAR,
  has_consent BOOLEAN,
  consent_record_id UUID,
  consented_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    k.consent_status,
    (k.consent_status = 'consented')::BOOLEAN,
    cr.id,
    cr.timestamp
  FROM public.kids k
  LEFT JOIN public.consent_records cr
    ON cr.user_id = k.parent_id
    AND k.id = ANY(cr.child_ids)
    AND cr.consent_type = 'child_data'
    AND cr.revoked_at IS NULL
  WHERE k.id = p_child_id
  LIMIT 1;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION public.get_child_consent_status(UUID) IS
'Returns consent status for a specific child.
Joins kids and consent_records to get most recent active consent.
Returns: status, has_consent (boolean), consent_record_id, consented_at timestamp.
Used for checking if child data can be processed.
Returns NULL rows if no consent found.';

-- Function: log_consent
-- Inserts a new consent record and returns the consent_id
-- Called by API/Edge Functions when parent gives consent
CREATE OR REPLACE FUNCTION public.log_consent(
  p_user_id UUID,
  p_consent_type VARCHAR,
  p_child_ids UUID[],
  p_consent_text TEXT,
  p_ip_address INET,
  p_user_agent TEXT
)
RETURNS UUID AS $$
DECLARE
  v_consent_id UUID;
BEGIN
  -- Validate consent_type
  IF p_consent_type NOT IN ('child_data', 'marketing') THEN
    RAISE EXCEPTION 'Invalid consent_type: %', p_consent_type;
  END IF;

  -- Validate user_id exists in profiles
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE id = p_user_id) THEN
    RAISE EXCEPTION 'user_id % does not exist in profiles', p_user_id;
  END IF;

  -- Validate all child_ids exist and belong to this user (if child_ids provided)
  IF array_length(p_child_ids, 1) > 0 THEN
    IF NOT EXISTS (
      SELECT 1
      FROM UNNEST(p_child_ids) AS child_id
      WHERE NOT EXISTS (
        SELECT 1 FROM public.kids WHERE id = child_id AND parent_id = p_user_id
      )
    ) THEN
      -- Only error if any child_id is invalid
      IF EXISTS (
        SELECT 1 FROM UNNEST(p_child_ids) AS child_id
        WHERE NOT EXISTS (
          SELECT 1 FROM public.kids WHERE id = child_id AND parent_id = p_user_id
        )
      ) THEN
        RAISE EXCEPTION 'One or more child_ids do not exist or do not belong to user %', p_user_id;
      END IF;
    END IF;
  END IF;

  -- Insert consent record
  INSERT INTO public.consent_records (
    user_id,
    consent_type,
    child_ids,
    consent_text,
    ip_address,
    user_agent
  ) VALUES (
    p_user_id,
    p_consent_type,
    p_child_ids,
    p_consent_text,
    p_ip_address,
    p_user_agent
  )
  RETURNING id INTO v_consent_id;

  -- Update child consent_status to 'consented' if child_data consent
  IF p_consent_type = 'child_data' AND array_length(p_child_ids, 1) > 0 THEN
    UPDATE public.kids
    SET consent_status = 'consented'
    WHERE id = ANY(p_child_ids) AND parent_id = p_user_id;
  END IF;

  RETURN v_consent_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.log_consent(UUID, VARCHAR, UUID[], TEXT, INET, TEXT) IS
'Logs a parental consent record (child_data or marketing).
Validates user_id, consent_type, and child_ids before inserting.
Updates kid.consent_status to ''consented'' for child_data consents.
Returns: consent_id (UUID) of the created record.
Called by: API endpoints or Edge Functions when parent gives consent.
Security: Must be called with service_role key (enforced by RLS).

Parameters:
  p_user_id: Parent/guardian UUID (must exist in profiles)
  p_consent_type: ''child_data'' or ''marketing''
  p_child_ids: Array of child UUIDs (empty array for marketing)
  p_consent_text: Exact consent text shown to parent (for audit trail)
  p_ip_address: Client IP address (INET type)
  p_user_agent: Client user agent string

Raises exceptions for:
  - Invalid consent_type
  - Non-existent user_id
  - Invalid or unauthorized child_ids';

-- Function: revoke_consent
-- Revokes a consent record by setting revoked_at timestamp
-- Updates child consent_status to 'consent_revoked'
CREATE OR REPLACE FUNCTION public.revoke_consent(
  p_consent_id UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS BOOLEAN AS $$
DECLARE
  v_user_id UUID;
  v_child_ids UUID[];
BEGIN
  -- Check that consent exists
  IF NOT EXISTS (SELECT 1 FROM public.consent_records WHERE id = p_consent_id) THEN
    RAISE EXCEPTION 'Consent record % does not exist', p_consent_id;
  END IF;

  -- Get consent details
  SELECT user_id, child_ids INTO v_user_id, v_child_ids
  FROM public.consent_records
  WHERE id = p_consent_id;

  -- Update revoked_at timestamp
  UPDATE public.consent_records
  SET revoked_at = CURRENT_TIMESTAMP
  WHERE id = p_consent_id AND revoked_at IS NULL;

  -- Update child consent_status to 'consent_revoked' if this was child_data consent
  IF array_length(v_child_ids, 1) > 0 THEN
    UPDATE public.kids
    SET consent_status = 'consent_revoked'
    WHERE id = ANY(v_child_ids) AND parent_id = v_user_id;
  END IF;

  RETURN true;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.revoke_consent(UUID, TEXT) IS
'Revokes a parental consent record by setting revoked_at timestamp.
Updates child.consent_status to ''consent_revoked'' for child_data consents.
Returns: true if successful.
Called by: API endpoints when parent revokes consent.
Security: Must be called with service_role key.

Parameters:
  p_consent_id: UUID of consent record to revoke
  p_reason: Optional reason for revocation (for audit purposes)

Raises exceptions for:
  - Non-existent consent_id
  - Consent already revoked (via WHERE revoked_at IS NULL check)';

-- ============================================================================
-- 6. NOTES & DESIGN DECISIONS
-- ============================================================================
-- 1. IMMUTABLE AUDIT TRAIL:
--    - consent_records has no UPDATE policy (RESTRICTIVE)
--    - Corrections require INSERT of new record and REVOKE of old record
--    - Preserves full history for GDPR compliance
--
-- 2. SOFT DELETE VIA REVOKED_AT:
--    - revoked_at column allows consent tracking even after revocation
--    - Supports "user consent history" queries
--    - Hard DELETE only by service role for GDPR data purge
--
-- 3. CHILD_IDS ARRAY:
--    - UUID[] type stores multiple child IDs per consent record
--    - GIN index for efficient array containment queries (ANY operator)
--    - Empty array for marketing consents (no children involved)
--    - Validates all children belong to parent in log_consent()
--
-- 4. IP_ADDRESS & USER_AGENT:
--    - INET type for IP addresses (supports network operations)
--    - Captured for fraud detection and GDPR audit purposes
--    - Helps identify suspicious consent patterns
--    - Can be cleared in GDPR data purge workflows
--
-- 5. CONSENT_STATUS ON KIDS:
--    - Denormalized from consent_records for query performance
--    - Four states: pending_consent, consented, consent_revoked, scheduled_for_deletion
--    - Used to enforce data processing permissions at application layer
--    - Must be kept in sync with consent_records via triggers/application logic
--
-- 6. RLS SECURITY:
--    - Users can only SELECT own consent records (privacy)
--    - Admins can SELECT all for compliance auditing
--    - Only service role can INSERT/DELETE (prevents client forgery)
--    - No UPDATE policy (immutable audit trail)
--
-- 7. PERFORMANCE INDEXES:
--    - idx_consent_records_user_id: Fast user lookups (foreign key)
--    - idx_consent_records_timestamp_desc: Recent events first
--    - idx_consent_records_child_ids: GIN for array containment (child_ids = ANY(...))
--    - idx_consent_records_user_timestamp: Composite for user history
--    - idx_consent_records_revoked_at: Partial index (only revoked records)
--
-- 8. GDPR COMPLIANCE:
--    - Consent text stored with record (versioning)
--    - IP address and user agent for audit trail
--    - Soft delete via revoked_at (preserves history)
--    - get_child_consent_status() for checking processing permissions
--    - log_consent() and revoke_consent() for structured consent management
--
-- ============================================================================
