-- Create Notification & Preference Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0011_create_notification_tables.sql
-- Description: Creates notifications and notification_preferences tables for managing user notifications
--              and notification delivery preferences with JSONB channel/frequency configuration
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Notification type enum for categorizing notifications
CREATE TYPE public.notification_type_enum AS ENUM (
  'match_found',        -- New toy match found in wishlist
  'request_received',   -- User received a new exchange request
  'exchange_status',    -- Update on exchange status (accepted, in_transit, etc.)
  'game_reward',        -- Game reward earned
  'message_received',   -- New chat message received
  'delivery_confirmed', -- Delivery confirmed in exchange
  'dispute_opened'      -- Dispute opened on exchange
);

-- ============================================================================
-- NOTIFICATIONS TABLE
-- ============================================================================
-- Stores all notifications for users with soft delete support
-- Implements GDPR-compliant notification logging with is_read tracking
-- Supports filtering by type and related items (toy, exchange)

CREATE TABLE IF NOT EXISTS public.notifications (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  related_toy_id UUID REFERENCES public.toys(id) ON DELETE SET NULL,
  related_exchange_id UUID REFERENCES public.exchanges(id) ON DELETE SET NULL,

  -- Notification Content
  type public.notification_type_enum NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,

  -- Status & Metadata
  is_read BOOLEAN NOT NULL DEFAULT false,

  -- Audit & Lifecycle Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE,  -- Soft delete for GDPR compliance

  -- Constraints
  CONSTRAINT valid_title CHECK (title <> ''),
  CONSTRAINT valid_body CHECK (body <> ''),
  CONSTRAINT valid_type CHECK (
    type IN ('match_found', 'request_received', 'exchange_status', 'game_reward',
             'message_received', 'delivery_confirmed', 'dispute_opened')
  )
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.notifications IS 'User notifications with soft delete support. Tracks all in-app notifications with read status and related item references.';
COMMENT ON COLUMN public.notifications.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.notifications.user_id IS 'UUID FK to profiles.id - notification recipient (CASCADE DELETE)';
COMMENT ON COLUMN public.notifications.related_toy_id IS 'UUID FK to toys.id - optional reference to toy (SET NULL on toy delete)';
COMMENT ON COLUMN public.notifications.related_exchange_id IS 'UUID FK to exchanges.id - optional reference to exchange (SET NULL on exchange delete)';
COMMENT ON COLUMN public.notifications.type IS 'Notification type enum (match_found, request_received, exchange_status, game_reward, message_received, delivery_confirmed, dispute_opened)';
COMMENT ON COLUMN public.notifications.title IS 'Notification title (short summary)';
COMMENT ON COLUMN public.notifications.body IS 'Notification body (detailed message)';
COMMENT ON COLUMN public.notifications.is_read IS 'Read status (false=unread, true=read). Updated when user views notification.';
COMMENT ON COLUMN public.notifications.created_at IS 'Timestamp when notification was created (auto-set on creation)';
COMMENT ON COLUMN public.notifications.deleted_at IS 'Soft delete timestamp (NULL=active, set to now() on deletion for GDPR)';

-- ============================================================================
-- NOTIFICATION_PREFERENCES TABLE
-- ============================================================================
-- Stores per-user notification delivery preferences with JSONB channel/frequency configuration
-- Implements quiet hours for child-safe notification timing
-- One row per user (UNIQUE user_id constraint)

CREATE TABLE IF NOT EXISTS public.notification_preferences (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Key (UNIQUE: one preference set per user)
  user_id UUID NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,

  -- Notification Type Preferences (JSONB with channel and frequency)
  -- Valid channel values: 'email', 'push', 'in_app'
  -- Valid frequency values: 'instant', 'daily_digest', 'weekly_digest', 'off'
  match_found JSONB NOT NULL DEFAULT '{"channel": "email", "frequency": "daily_digest"}',
  request_received JSONB NOT NULL DEFAULT '{"channel": "push", "frequency": "instant"}',
  exchange_status JSONB NOT NULL DEFAULT '{"channel": "push", "frequency": "instant"}',
  game_reward JSONB NOT NULL DEFAULT '{"channel": "in_app", "frequency": "instant"}',
  message_received JSONB NOT NULL DEFAULT '{"channel": "push", "frequency": "instant"}',
  delivery_confirmed JSONB NOT NULL DEFAULT '{"channel": "push", "frequency": "instant"}',
  dispute_opened JSONB NOT NULL DEFAULT '{"channel": "push", "frequency": "instant"}',

  -- Quiet Hours (optional time window to suppress non-critical notifications)
  quiet_hours_start TIME,
  quiet_hours_end TIME,

  -- Audit Timestamp
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_match_found CHECK (
    match_found ? 'channel' AND match_found ? 'frequency'
  ),
  CONSTRAINT valid_request_received CHECK (
    request_received ? 'channel' AND request_received ? 'frequency'
  ),
  CONSTRAINT valid_exchange_status CHECK (
    exchange_status ? 'channel' AND exchange_status ? 'frequency'
  ),
  CONSTRAINT valid_game_reward CHECK (
    game_reward ? 'channel' AND game_reward ? 'frequency'
  ),
  CONSTRAINT valid_message_received CHECK (
    message_received ? 'channel' AND message_received ? 'frequency'
  ),
  CONSTRAINT valid_delivery_confirmed CHECK (
    delivery_confirmed ? 'channel' AND delivery_confirmed ? 'frequency'
  ),
  CONSTRAINT valid_dispute_opened CHECK (
    dispute_opened ? 'channel' AND dispute_opened ? 'frequency'
  ),
  CONSTRAINT valid_quiet_hours CHECK (
    (quiet_hours_start IS NULL AND quiet_hours_end IS NULL) OR
    (quiet_hours_start IS NOT NULL AND quiet_hours_end IS NOT NULL AND quiet_hours_start < quiet_hours_end)
  )
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.notification_preferences IS 'Per-user notification delivery preferences. One row per user with JSONB channel/frequency config for each notification type. Implements quiet hours for child-safe notification timing.';
COMMENT ON COLUMN public.notification_preferences.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.notification_preferences.user_id IS 'UUID FK to profiles.id (UNIQUE: one preference row per user, CASCADE DELETE)';
COMMENT ON COLUMN public.notification_preferences.match_found IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.request_received IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.exchange_status IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.game_reward IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.message_received IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.delivery_confirmed IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.dispute_opened IS 'JSONB {"channel": "email|push|in_app", "frequency": "instant|daily_digest|weekly_digest|off"}';
COMMENT ON COLUMN public.notification_preferences.quiet_hours_start IS 'Optional start time for quiet hours (no non-critical notifications before this time)';
COMMENT ON COLUMN public.notification_preferences.quiet_hours_end IS 'Optional end time for quiet hours (no non-critical notifications after this time)';
COMMENT ON COLUMN public.notification_preferences.updated_at IS 'Timestamp when preferences were last updated (auto-set on creation, manual update on change)';

-- ============================================================================
-- INDEXES - Strategic for query performance
-- ============================================================================

-- Notifications table indexes
-- Fast lookup of all notifications for a user (common query: "get my notifications")
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);

-- Fast filtering notifications by creation date (pagination, recent notifications first)
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);

-- Composite index: user_id + created_at (find user's recent notifications efficiently)
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON public.notifications(user_id, created_at DESC);

-- Fast filtering unread notifications for a user (notification badge count)
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications(user_id, is_read) WHERE is_read = false;

-- Fast lookup of notifications related to a toy (show all notifications for toy)
CREATE INDEX IF NOT EXISTS idx_notifications_toy_id ON public.notifications(related_toy_id) WHERE related_toy_id IS NOT NULL;

-- Fast lookup of notifications related to an exchange (show all notifications for exchange)
CREATE INDEX IF NOT EXISTS idx_notifications_exchange_id ON public.notifications(related_exchange_id) WHERE related_exchange_id IS NOT NULL;

-- Fast soft-delete queries (exclude deleted notifications)
CREATE INDEX IF NOT EXISTS idx_notifications_not_deleted ON public.notifications(user_id, deleted_at) WHERE deleted_at IS NULL;

-- Notification preferences table
-- No additional indexes needed beyond user_id UNIQUE constraint (already indexed)

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on both tables (policies will be created separately in rls_policies.sql)
-- RLS ensures users can only see their own notifications and preferences

-- Enable RLS on notifications table
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Enable RLS on notification_preferences table
ALTER TABLE public.notification_preferences ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- 1. Soft Delete Strategy:
--    - notifications.deleted_at is NULL for active notifications
--    - Queries should filter: WHERE deleted_at IS NULL to exclude soft-deleted records
--    - Supports GDPR data deletion workflows and audit trails
--    - Index idx_notifications_not_deleted optimizes soft-delete queries
--
-- 2. JSONB Structure for Preferences:
--    - Each notification type has a JSONB column with "channel" and "frequency" keys
--    - Example: '{"channel": "push", "frequency": "instant"}'
--    - CHECK constraints validate both keys are present
--    - Application can extend with additional keys (e.g., "do_not_disturb", "quiet_hours")
--
-- 3. Quiet Hours Implementation:
--    - quiet_hours_start and quiet_hours_end are TIME values (24h format)
--    - Both must be set or both must be NULL (constraint valid_quiet_hours)
--    - If set, non-critical notifications suppressed outside quiet hours
--    - Example: quiet_hours_start = '22:00', quiet_hours_end = '08:00' (bedtime)
--
-- 4. Related Item References:
--    - related_toy_id and related_exchange_id are nullable FKs
--    - Allow notifications to be linked to toys/exchanges for context
--    - Useful for UI: "Show me all notifications about this toy"
--    - SET NULL on delete preserves notification history
--
-- 5. Notification Types:
--    - match_found: New toy match in wishlist (email/daily typical)
--    - request_received: Someone requested user's toy (push/instant critical)
--    - exchange_status: Status updates on user's exchanges (push/instant)
--    - game_reward: Game reward earned (in_app/instant)
--    - message_received: Chat message received (push/instant)
--    - delivery_confirmed: Delivery confirmed (push/instant)
--    - dispute_opened: Dispute opened on exchange (push/instant)
--
-- 6. Indexes Strategy:
--    - idx_notifications_user_id: FK index for basic user notifications queries
--    - idx_notifications_created_at: Time-based pagination
--    - idx_notifications_user_created: Composite for "user's recent notifications"
--    - idx_notifications_user_unread: Filtered index for unread count (very selective)
--    - idx_notifications_toy_id: Partial index for toy-related notifications
--    - idx_notifications_exchange_id: Partial index for exchange-related notifications
--    - idx_notifications_not_deleted: Partial index optimizes soft-delete queries
--
-- 7. RLS Policies:
--    - Will be created in separate migration: supabase/migrations/*_rls_policies.sql
--    - Policies ensure users can only see/modify their own notifications and preferences
--    - Child-safe: Parental controls enforced at application layer
--
-- 8. Foreign Keys:
--    - user_id: CASCADE DELETE (if user deleted, all notifications/preferences deleted)
--    - related_toy_id: SET NULL (preserve notification history if toy deleted)
--    - related_exchange_id: SET NULL (preserve notification history if exchange deleted)
--
-- 9. Performance Considerations:
--    - Unread notification count uses filtered index for fast DISTINCT queries
--    - Partial indexes (WHERE clauses) reduce index size and write overhead
--    - JSONB columns support efficient querying via @> operator
--    - Denormalization via is_read boolean avoids JSON parsing in WHERE clauses
--
-- 10. GDPR Compliance:
--     - Soft delete via deleted_at supports GDPR data retention policies
--     - Quiet hours respect child-safe notification timing requirements
--     - Preference storage allows users to control notification delivery
--
