-- Create Wishlist & Matching Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0006_create_wishlist_matching_tables.sql
-- Description: Creates wishlists, wishlist_items, and matching_log tables for toy recommendations
--              and preference tracking. Implements matching algorithm logging and preference
--              management for improved toy discovery and exchange matching.
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- WISHLISTS TABLE
-- ============================================================================
-- Stores one wishlist per kid (1:1 relationship with kids table)
-- Each kid can have multiple items in their wishlist via wishlist_items table
-- Relationship: One wishlists row per kid; many wishlist_items per wishlist

CREATE TABLE IF NOT EXISTS public.wishlists (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  kid_id UUID NOT NULL UNIQUE REFERENCES public.kids(id) ON DELETE CASCADE,  -- One wishlist per kid (UNIQUE constraint)

  -- Audit Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.wishlists IS 'One wishlist per kid. Stores the parent container for a kids wishes and preferences. One-to-one relationship with kids table via UNIQUE kid_id constraint.';
COMMENT ON COLUMN public.wishlists.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.wishlists.kid_id IS 'UUID FK to kids.id - the kid this wishlist belongs to. UNIQUE constraint ensures one wishlist per kid (CASCADE DELETE)';
COMMENT ON COLUMN public.wishlists.created_at IS 'Timestamp when wishlist was created (auto-set on INSERT)';
COMMENT ON COLUMN public.wishlists.updated_at IS 'Timestamp when wishlist was last updated (auto-set on INSERT and UPDATE)';

-- ============================================================================
-- WISHLIST_ITEMS TABLE
-- ============================================================================
-- Stores individual items in a kid's wishlist
-- Each item can reference either an existing toy (toy_id) or a custom text wish (custom_wish_text)
-- CHECK constraint ensures exactly one of these is provided (XOR logic)
-- priority_order determines the ranking of wishes (1 = most wanted, 2 = second, etc.)

CREATE TABLE IF NOT EXISTS public.wishlist_items (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  wishlist_id UUID NOT NULL REFERENCES public.wishlists(id) ON DELETE CASCADE,  -- Wishlist this item belongs to
  toy_id UUID REFERENCES public.toys(id) ON DELETE SET NULL,                   -- Reference to existing toy (nullable for custom wishes)

  -- Wish Content (Either toy_id OR custom_wish_text must be non-null)
  custom_wish_text TEXT,  -- Custom wish text entered by kid/parent (nullable for toy references)

  -- Preference Filters
  category_preference VARCHAR(255),  -- Preferred toy category (e.g., "action_figures", "puzzles", "board_games")
  tag_preferences TEXT[],            -- Array of preferred tags (e.g., ARRAY['educational', 'outdoor'])
  condition_preference VARCHAR(20) DEFAULT 'any',  -- Preferred toy condition: 'any', 'like_new', 'good_plus', 'good'

  -- Ordering
  priority_order INT NOT NULL,  -- Integer priority (1 = highest priority, ascending order)

  -- Audit Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT toy_or_custom_wish_xor CHECK (
    (toy_id IS NOT NULL AND custom_wish_text IS NULL) OR
    (toy_id IS NULL AND custom_wish_text IS NOT NULL)
  ),  -- Exactly one of toy_id or custom_wish_text must be provided (not both, not neither)
  CONSTRAINT valid_custom_wish_text CHECK (
    custom_wish_text IS NULL OR (LENGTH(custom_wish_text) > 0 AND LENGTH(custom_wish_text) <= 500)
  ),  -- Custom wish text must be 1-500 chars if provided
  CONSTRAINT valid_category CHECK (
    category_preference IS NULL OR (LENGTH(category_preference) > 0 AND LENGTH(category_preference) <= 255)
  ),  -- Category must be non-empty and <= 255 chars
  CONSTRAINT valid_priority_order CHECK (priority_order > 0),  -- Priority must be positive integer
  CONSTRAINT valid_condition CHECK (
    condition_preference IN ('any', 'like_new', 'good_plus', 'good')
  ),  -- Condition must be one of allowed enum values
  UNIQUE (wishlist_id, priority_order)  -- Unique: cannot have duplicate priority_orders in same wishlist
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.wishlist_items IS 'Individual wish items in a kids wishlist. Each item references either an existing toy or a custom wish text. Enforced via XOR CHECK constraint: either toy_id OR custom_wish_text is non-null (but not both). Unique (wishlist_id, priority_order) ensures no duplicate priorities.';
COMMENT ON COLUMN public.wishlist_items.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.wishlist_items.wishlist_id IS 'UUID FK to wishlists.id - the wishlist this item belongs to (CASCADE DELETE)';
COMMENT ON COLUMN public.wishlist_items.toy_id IS 'UUID FK to toys.id - the toy being wished for. NULL if custom_wish_text is provided (SET NULL on toy deletion)';
COMMENT ON COLUMN public.wishlist_items.custom_wish_text IS 'Custom wish text (1-500 chars) for wishes not matching an existing toy. NULL if toy_id is provided';
COMMENT ON COLUMN public.wishlist_items.category_preference IS 'Optional preferred toy category (e.g., "action_figures", "board_games", "puzzles") - max 255 chars';
COMMENT ON COLUMN public.wishlist_items.tag_preferences IS 'Optional array of preferred tags (e.g., ARRAY[''educational'', ''outdoor''])';
COMMENT ON COLUMN public.wishlist_items.condition_preference IS 'Preferred condition of toy: ''any'' (default), ''like_new'', ''good_plus'', or ''good''';
COMMENT ON COLUMN public.wishlist_items.priority_order IS 'Priority ranking (1 = most wanted, 2 = second, etc.). Must be positive integer. Unique per wishlist.';
COMMENT ON COLUMN public.wishlist_items.created_at IS 'Timestamp when wishlist item was created';
COMMENT ON COLUMN public.wishlist_items.updated_at IS 'Timestamp when wishlist item was last updated';

-- ============================================================================
-- MATCHING_LOG TABLE
-- ============================================================================
-- Stores the results of matching algorithm runs
-- Tracks which toys were suggested for each wishlist item and their match score (0.00-1.00)
-- Enables analysis of matching effectiveness and audit trail of recommendations

CREATE TABLE IF NOT EXISTS public.matching_log (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  wishlist_item_id UUID NOT NULL REFERENCES public.wishlist_items(id) ON DELETE CASCADE,  -- Item being matched
  matched_toy_id UUID NOT NULL REFERENCES public.toys(id) ON DELETE CASCADE,              -- Toy suggested as a match

  -- Matching Score
  score NUMERIC(3, 2) NOT NULL,  -- Match score between 0.00 and 1.00 (NUMERIC(3,2) allows exactly 2 decimal places)

  -- Audit Timestamps
  scored_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_score_range CHECK (score >= 0.00 AND score <= 1.00)  -- Score must be between 0.00 and 1.00
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.matching_log IS 'Records matching algorithm results. Each row represents a toy that was scored/matched against a wishlist item. Score is NUMERIC(3, 2) representing 0.00 to 1.00. Enables analysis of matching effectiveness and provides audit trail.';
COMMENT ON COLUMN public.matching_log.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.matching_log.wishlist_item_id IS 'UUID FK to wishlist_items.id - the wish item being matched (CASCADE DELETE)';
COMMENT ON COLUMN public.matching_log.matched_toy_id IS 'UUID FK to toys.id - the toy that was scored as a match (CASCADE DELETE)';
COMMENT ON COLUMN public.matching_log.score IS 'Match score as NUMERIC(3, 2): ranges from 0.00 (no match) to 1.00 (perfect match). Enforced via CHECK constraint.';
COMMENT ON COLUMN public.matching_log.scored_at IS 'Timestamp when the match was scored by the algorithm';

-- ============================================================================
-- TRIGGER FUNCTION FOR UPDATED_AT TIMESTAMPS
-- ============================================================================

-- Auto-update wishlists.updated_at on any UPDATE to wishlists table
CREATE OR REPLACE FUNCTION public.update_wishlists_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Auto-update wishlist_items.updated_at on any UPDATE to wishlist_items table
CREATE OR REPLACE FUNCTION public.update_wishlist_items_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger 1: Auto-update wishlists.updated_at on any modification
CREATE TRIGGER trg_update_wishlists_updated_at
BEFORE UPDATE ON public.wishlists
FOR EACH ROW
EXECUTE FUNCTION public.update_wishlists_updated_at();

-- Trigger 2: Auto-update wishlist_items.updated_at on any modification
CREATE TRIGGER trg_update_wishlist_items_updated_at
BEFORE UPDATE ON public.wishlist_items
FOR EACH ROW
EXECUTE FUNCTION public.update_wishlist_items_updated_at();

-- ============================================================================
-- INDEXES - Strategic for query performance
-- ============================================================================

-- Wishlists table indexes
-- Fast lookup of wishlist by kid_id (kid_id is already UNIQUE, provides primary index)
-- No additional index needed as UNIQUE constraint creates an index

-- Wishlist_items table indexes
-- Fast lookup of items in a specific wishlist, ordered by priority
CREATE INDEX IF NOT EXISTS idx_wishlist_items_wishlist_priority ON public.wishlist_items(wishlist_id, priority_order);

-- Fast lookup of items matching a specific toy (for toy deletion cascade or toy activity queries)
CREATE INDEX IF NOT EXISTS idx_wishlist_items_toy_id ON public.wishlist_items(toy_id);

-- Fast search of custom wishes by text (for searching/filtering wishlist)
CREATE INDEX IF NOT EXISTS idx_wishlist_items_custom_wish_text ON public.wishlist_items USING GIN(to_tsvector('english', custom_wish_text));

-- Matching_log table indexes
-- Fast lookup of all matches for a specific wishlist item, ordered by score (descending)
CREATE INDEX IF NOT EXISTS idx_matching_log_item_scored ON public.matching_log(wishlist_item_id, scored_at DESC);

-- Fast lookup of all times a specific toy was matched (for toy popularity/analytics)
CREATE INDEX IF NOT EXISTS idx_matching_log_toy_id ON public.matching_log(matched_toy_id);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on wishlist tables (policies will be created separately in Task 2.9)
-- RLS ensures users can only see wishlists and items for their own children

-- Enable RLS on wishlists table
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Enable RLS on wishlist_items table
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;

-- Enable RLS on matching_log table
ALTER TABLE public.matching_log ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- 1. Wishlists Schema:
--    - One wishlist per kid (UNIQUE kid_id constraint)
--    - TIMESTAMP WITH TIME ZONE for all audit fields (timezone-aware for global platform)
--    - CASCADE DELETE: if kid is deleted, wishlist and all items are deleted
--
-- 2. Wishlist Items Constraints:
--    - toy_or_custom_wish_xor: Exactly one of toy_id or custom_wish_text must be non-null
--      * This is XOR logic: (A AND NOT B) OR (NOT A AND B)
--      * Ensures each wish is either a reference to existing toy OR custom text (not both)
--    - valid_custom_wish_text: Custom wishes must be 1-500 characters
--    - valid_category: Category preference max 255 characters
--    - valid_priority_order: Priority must be > 0 (positive integers only)
--    - valid_condition: Condition must be one of: 'any', 'like_new', 'good_plus', 'good'
--    - UNIQUE (wishlist_id, priority_order): Cannot have duplicate priorities in same wishlist
--      * Allows reordering without key violations by incrementing/decrementing priorities
--
-- 3. Matching Log:
--    - score NUMERIC(3, 2): Fixed-point decimal with 3 total digits, 2 decimal places
--      * Allows values from 0.00 to 99.99, but CHECK constraint limits to 0.00-1.00
--      * More precise than FLOAT; suitable for scoring algorithms
--    - scored_at: Timestamp when match was generated (for analytics/auditing)
--    - CASCADE DELETE: If wishlist_item or toy is deleted, matching_log records are deleted
--
-- 4. Trigger Functions:
--    - update_wishlists_updated_at(): Auto-sets updated_at to CURRENT_TIMESTAMP before UPDATE
--    - update_wishlist_items_updated_at(): Auto-sets updated_at to CURRENT_TIMESTAMP before UPDATE
--    - Triggers fire BEFORE UPDATE to capture the new timestamp
--
-- 5. Indexes Strategy:
--    - (wishlist_id, priority_order): Composite index for fast retrieval of items in a wishlist
--      * Supports queries like: SELECT * FROM wishlist_items WHERE wishlist_id = ? ORDER BY priority_order
--      * Also used for UNIQUE constraint enforcement
--    - toy_id: Single index for fast lookup of all wishlists containing a toy
--      * Used when a toy is deleted or for toy popularity analysis
--    - custom_wish_text (GIN + tsvector): Full-text search on custom wishes
--      * Enables efficient ILIKE or FTS queries on wish descriptions
--      * GIN index type optimal for text search
--    - (wishlist_item_id, scored_at DESC): Composite for fast retrieval of matches ordered by recency
--      * Supports queries like: SELECT * FROM matching_log WHERE wishlist_item_id = ? ORDER BY scored_at DESC
--      * DESC ordering optimizes for "get latest matches" queries
--    - matched_toy_id: Single index for fast lookup of all matches for a toy
--      * Used for toy activity/analytics queries
--
-- 6. Priority Order Design:
--    - Allows any positive integer (1, 2, 3... or 10, 20, 30...)
--    - Supports efficient reordering without renumbering all items
--    - Example: Can insert new item at priority 15 between 10 and 20 without shifting others
--    - UNIQUE constraint ensures no gaps in user-visible ordering
--    - Application layer can handle sorting/renumbering if needed
--
-- 7. Preference Filters:
--    - category_preference: Single category preference (e.g., "action_figures")
--    - tag_preferences: Array of tags for more flexible filtering (e.g., ARRAY['educational', 'outdoor'])
--    - condition_preference: Specifies desired toy condition (defaults to 'any')
--    - These fields guide the matching algorithm but are optional
--
-- 8. Matching Algorithm Notes:
--    - score NUMERIC(3, 2) precision allows fine-grained matching (0.01 increments)
--    - Algorithm can use category, tags, and condition to calculate score
--    - Multiple matches per wishlist_item allowed (one row per matched toy)
--    - Logs enable A/B testing of different matching strategies
--
-- 9. RLS Policies:
--    - Will be created in separate migration: Task 2.9
--    - Policies ensure:
--      * Users can only see wishlists and items for their own kids
--      * Matching logs are visible only to relevant parties
--      * Admins can access all data for analytics
--
-- 10. Future Enhancements:
--     - Add match_type column (automatic vs manual suggestion)
--     - Add feedback column for user rating of matches
--     - Add match_status (pending review, accepted, rejected, completed)
--     - Add comment column for notes about match
--     - Create materialized view for "best matches per wishlist"
--     - Add stored procedure for automated matching algorithm
--     - Add match_algorithm_version for tracking algorithm improvements
