-- Create Core Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_create_core_tables.sql
-- Description: Creates profiles and kids tables with enums, constraints, and RLS support

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Age group enum for categorizing children
CREATE TYPE public.age_group_enum AS ENUM (
  '0-2',    -- Infants and toddlers
  '3-5',    -- Preschool
  '6-8',    -- Early primary
  '9-11',   -- Late primary
  '12-14',  -- Early adolescence
  '15+'     -- Teens and older children
);

-- Kid status enum for soft deletes and visibility management
CREATE TYPE public.kid_status_enum AS ENUM (
  'active',   -- Child is active and visible
  'hidden',   -- Child is hidden but data preserved (parental control)
  'deleted'   -- Child is marked for deletion (GDPR compliance)
);

-- ============================================================================
-- PROFILES TABLE
-- ============================================================================
-- Stores parent/guardian user information
-- This table references auth.users for authentication

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  full_name TEXT,
  language VARCHAR(2) DEFAULT 'en' NOT NULL,
  notification_preference JSONB DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add comment for documentation
COMMENT ON TABLE public.profiles IS 'Parent/guardian user profiles linked to Supabase auth';
COMMENT ON COLUMN public.profiles.id IS 'UUID primary key, references auth.users.id';
COMMENT ON COLUMN public.profiles.email IS 'Unique email address for the parent/guardian';
COMMENT ON COLUMN public.profiles.full_name IS 'Full name of the parent/guardian';
COMMENT ON COLUMN public.profiles.language IS 'User language preference (ISO 639-1 code, default: en)';
COMMENT ON COLUMN public.profiles.notification_preference IS 'JSONB storing user notification preferences';
COMMENT ON COLUMN public.profiles.created_at IS 'Timestamp when profile was created';
COMMENT ON COLUMN public.profiles.updated_at IS 'Timestamp when profile was last updated';

-- ============================================================================
-- KIDS TABLE
-- ============================================================================
-- Stores child/dependent information for parents/guardians
-- Implements soft delete via status column for GDPR compliance

CREATE TABLE IF NOT EXISTS public.kids (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  parent_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  birthdate DATE,
  age_group public.age_group_enum GENERATED ALWAYS AS (
    CASE
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 3 THEN '0-2'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 6 THEN '3-5'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 9 THEN '6-8'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 12 THEN '9-11'::public.age_group_enum
      WHEN EXTRACT(YEAR FROM age(birthdate)) < 15 THEN '12-14'::public.age_group_enum
      ELSE '15+'::public.age_group_enum
    END
  ) STORED,
  interests TEXT[] DEFAULT ARRAY[]::TEXT[],
  allergies TEXT,
  status public.kid_status_enum DEFAULT 'active' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_age_group CHECK (age_group IN ('0-2', '3-5', '6-8', '9-11', '12-14', '15+')),
  CONSTRAINT valid_status CHECK (status IN ('active', 'hidden', 'deleted')),
  CONSTRAINT valid_birthdate CHECK (birthdate <= CURRENT_DATE)
);

-- Add comments for documentation
COMMENT ON TABLE public.kids IS 'Child/dependent profiles owned by parent/guardian (profiles)';
COMMENT ON COLUMN public.kids.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.kids.parent_id IS 'UUID foreign key to profiles.id';
COMMENT ON COLUMN public.kids.name IS 'Child name';
COMMENT ON COLUMN public.kids.birthdate IS 'Child birthdate (DATE format)';
COMMENT ON COLUMN public.kids.age_group IS 'Computed age group (0-2, 3-5, 6-8, 9-11, 12-14, 15+) from birthdate';
COMMENT ON COLUMN public.kids.interests IS 'Array of interest tags (e.g., ARRAY[''sports'', ''art''])';
COMMENT ON COLUMN public.kids.allergies IS 'Optional allergy information';
COMMENT ON COLUMN public.kids.status IS 'Soft delete status (active, hidden, deleted)';
COMMENT ON COLUMN public.kids.created_at IS 'Timestamp when record was created';
COMMENT ON COLUMN public.kids.updated_at IS 'Timestamp when record was last updated';

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Optimize queries on frequently filtered/joined columns

-- Index on kids.parent_id for efficient lookups of children by parent
CREATE INDEX IF NOT EXISTS idx_kids_parent_id ON public.kids(parent_id);

-- Index on kids.status for efficient soft delete queries (e.g., WHERE status = 'active')
CREATE INDEX IF NOT EXISTS idx_kids_status ON public.kids(status);

-- Composite index on parent_id and status for common query pattern
CREATE INDEX IF NOT EXISTS idx_kids_parent_status ON public.kids(parent_id, status);

-- Index on profiles.email for authentication lookups
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);

-- ============================================================================
-- VIEW: user_age_groups
-- ============================================================================
-- Aggregates kids by age group for statistics and insights

CREATE OR REPLACE VIEW public.user_age_groups AS
SELECT
  k.parent_id,
  k.age_group,
  COUNT(k.id) AS child_count,
  ARRAY_AGG(k.id) FILTER (WHERE k.status = 'active') AS active_child_ids,
  COUNT(k.id) FILTER (WHERE k.status = 'active') AS active_count,
  COUNT(k.id) FILTER (WHERE k.status = 'hidden') AS hidden_count,
  COUNT(k.id) FILTER (WHERE k.status = 'deleted') AS deleted_count,
  MAX(k.updated_at) AS last_updated
FROM public.kids k
GROUP BY k.parent_id, k.age_group;

COMMENT ON VIEW public.user_age_groups IS 'Aggregated view of kids grouped by age_group per parent_id';

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on both tables for user data isolation

-- Enable RLS on profiles table
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Enable RLS on kids table
ALTER TABLE public.kids ENABLE ROW LEVEL SECURITY;

-- Enable RLS on view (inherits from underlying tables)
ALTER VIEW public.user_age_groups SET (security_barrier = on);

-- ============================================================================
-- Notes:
-- ============================================================================
-- 1. RLS policies are NOT created in this migration. They will be added separately in:
--    supabase/policies/rls_policies.sql
--
-- 2. The age_group column is a GENERATED ALWAYS AS (STORED) column that automatically
--    calculates age from birthdate. This ensures age_group is always in sync with birthdate.
--
-- 3. Soft delete via status column allows GDPR data deletion workflows:
--    - status = 'active': Child visible to parent
--    - status = 'hidden': Child data preserved but not visible (parental choice)
--    - status = 'deleted': Child marked for permanent deletion (GDPR request)
--
-- 4. The user_age_groups view is useful for:
--    - Parent dashboard showing children by age group
--    - Admin analytics on platform age demographics
--    - Filtering toy recommendations by age appropriateness
--
-- 5. Indexes are strategic:
--    - idx_kids_parent_id: Fast lookup of children by parent (frequent query)
--    - idx_kids_status: Fast filtering by soft delete status
--    - idx_kids_parent_status: Composite for common "active children of parent" query
--    - idx_profiles_email: Support authentication lookups
