-- Create Exchange & Escrow Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0004_create_exchange_escrow_tables.sql
-- Description: Creates exchanges, delivery_confirmations, and disputes tables with escrow mechanism,
--              status tracking, and dispute handling for the ticket economy system
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Exchange status enum for lifecycle management
-- Defines valid states through the complete exchange workflow
CREATE TYPE public.exchange_status_enum AS ENUM (
  'pending_request',   -- Initial request from requester awaiting lister decision
  'accepted',          -- Lister has accepted the exchange request
  'in_transit',        -- Toy is being shipped to requester
  'delivered',         -- Toy has been received by requester (awaiting confirmation)
  'confirmed',         -- Delivery confirmed, exchange is verified and tickets ready to release
  'completed',         -- Exchange fully completed, tickets transferred and released from escrow
  'disputed',          -- Dispute has been opened during this exchange
  'auto_completed',    -- Exchange auto-completed after 48h timeout without confirmation
  'canceled'           -- Exchange was canceled (soft delete for audit trail)
);

-- Condition enum for delivery confirmation - tracks toy condition at delivery
CREATE TYPE public.condition_enum AS ENUM (
  'like_listed',       -- Toy matches listed condition exactly
  'minor_wear',        -- Minimal additional wear since listing
  'damage',            -- Noticeable damage not mentioned in listing
  'missing_parts'      -- Parts missing from the toy
);

-- Dispute status enum for resolution tracking
CREATE TYPE public.dispute_status_enum AS ENUM (
  'open',              -- Dispute recently created, awaiting admin review
  'admin_review',      -- Admin actively reviewing dispute
  'resolved',          -- Admin has made resolution decision
  'closed'             -- Dispute fully closed (resolution implemented)
);

-- ============================================================================
-- EXCHANGES TABLE
-- ============================================================================
-- Stores all exchange transactions (core of the ticket economy escrow system)
-- Implements soft delete via status='canceled' (no hard deletes for audit trail)
-- Tracks exchange lifecycle from request to completion
-- Timestamps mark critical state transitions for audit and analytics

CREATE TABLE IF NOT EXISTS public.exchanges (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys (all with CASCADE DELETE for data consistency)
  requester_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,  -- User requesting the toy
  lister_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,     -- User listing the toy
  toy_id UUID NOT NULL REFERENCES public.toys(id) ON DELETE CASCADE,             -- The toy being exchanged (immutable after creation)
  kid_for_id UUID NOT NULL REFERENCES public.kids(id) ON DELETE CASCADE,         -- Child the toy is intended for (requester's child)

  -- Exchange Status & Lifecycle
  status public.exchange_status_enum NOT NULL DEFAULT 'pending_request',

  -- User Communication
  requester_message TEXT,  -- Optional message from requester to lister (shown in request)

  -- Audit & Lifecycle Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  accepted_at TIMESTAMP WITH TIME ZONE,            -- When lister accepted the request
  delivery_confirmed_at TIMESTAMP WITH TIME ZONE,  -- When delivery was confirmed/verified
  completed_at TIMESTAMP WITH TIME ZONE,           -- When exchange was fully completed

  -- Constraints
  CONSTRAINT valid_status CHECK (
    status IN ('pending_request', 'accepted', 'in_transit', 'delivered', 'confirmed',
               'completed', 'disputed', 'auto_completed', 'canceled')
  ),
  CONSTRAINT requester_not_lister CHECK (requester_id != lister_id),  -- Prevent self-exchange
  CONSTRAINT non_empty_message CHECK (requester_message IS NULL OR requester_message <> '')
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.exchanges IS 'Core exchange transaction records - implements escrow mechanism for ticket economy. Soft-delete via status=canceled preserves audit trail.';
COMMENT ON COLUMN public.exchanges.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.exchanges.requester_id IS 'UUID FK to profiles.id - user requesting the toy';
COMMENT ON COLUMN public.exchanges.lister_id IS 'UUID FK to profiles.id - user listing the toy (ticket receiver when completed)';
COMMENT ON COLUMN public.exchanges.toy_id IS 'UUID FK to toys.id - toy being exchanged (immutable after creation)';
COMMENT ON COLUMN public.exchanges.kid_for_id IS 'UUID FK to kids.id - child profile toy is intended for';
COMMENT ON COLUMN public.exchanges.status IS 'Exchange lifecycle status (pending_request -> accepted -> in_transit -> delivered -> confirmed -> completed)';
COMMENT ON COLUMN public.exchanges.requester_message IS 'Optional message from requester to lister explaining why they want the toy';
COMMENT ON COLUMN public.exchanges.created_at IS 'Timestamp when exchange request was created (escrow starts here)';
COMMENT ON COLUMN public.exchanges.updated_at IS 'Timestamp when exchange was last updated';
COMMENT ON COLUMN public.exchanges.accepted_at IS 'Timestamp when lister accepted the request';
COMMENT ON COLUMN public.exchanges.delivery_confirmed_at IS 'Timestamp when delivery was confirmed (tickets released from escrow)';
COMMENT ON COLUMN public.exchanges.completed_at IS 'Timestamp when exchange fully completed (all state transitions done)';

-- ============================================================================
-- DELIVERY_CONFIRMATIONS TABLE
-- ============================================================================
-- Tracks toy condition at delivery (1:1 relationship with exchanges)
-- Records physical inspection details for dispute prevention & resolution
-- Unique constraint ensures each exchange has at most one delivery confirmation

CREATE TABLE IF NOT EXISTS public.delivery_confirmations (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Key (unique: each exchange has exactly one delivery confirmation)
  exchange_id UUID NOT NULL UNIQUE REFERENCES public.exchanges(id) ON DELETE CASCADE,

  -- Delivery Details
  condition_received public.condition_enum NOT NULL,  -- Actual toy condition received
  photos_count INT NOT NULL DEFAULT 0,                 -- Count of photos uploaded as proof
  notes TEXT,                                          -- Detailed notes from recipient

  -- Confirmation Timestamp
  confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_condition CHECK (
    condition_received IN ('like_listed', 'minor_wear', 'damage', 'missing_parts')
  ),
  CONSTRAINT valid_photos_count CHECK (photos_count >= 0),
  CONSTRAINT non_empty_notes CHECK (notes IS NULL OR notes <> '')
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.delivery_confirmations IS 'Delivery confirmation records linked 1:1 to exchanges. Records toy condition and proof photos at delivery point.';
COMMENT ON COLUMN public.delivery_confirmations.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.delivery_confirmations.exchange_id IS 'UUID FK to exchanges.id (UNIQUE: one confirmation per exchange, CASCADE DELETE)';
COMMENT ON COLUMN public.delivery_confirmations.condition_received IS 'Actual condition of toy when received (like_listed, minor_wear, damage, missing_parts)';
COMMENT ON COLUMN public.delivery_confirmations.photos_count IS 'Count of proof photos uploaded (cached denormalization for query performance)';
COMMENT ON COLUMN public.delivery_confirmations.notes IS 'Optional detailed notes about condition, damage, or discrepancies';
COMMENT ON COLUMN public.delivery_confirmations.confirmed_at IS 'Timestamp when delivery was confirmed (auto-set on creation)';

-- ============================================================================
-- DISPUTES TABLE
-- ============================================================================
-- Tracks disputes that arise during or after exchanges
-- Can only be created for exchanges with delivery confirmation (verified delivery required)
-- Implements dispute resolution workflow: open -> admin_review -> resolved -> closed

CREATE TABLE IF NOT EXISTS public.disputes (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  exchange_id UUID NOT NULL REFERENCES public.exchanges(id) ON DELETE CASCADE,  -- The disputed exchange
  reported_by_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,  -- User who reported issue

  -- Dispute Details
  reason VARCHAR(50) NOT NULL,      -- Category of dispute (damage, wrong_item, not_received, misrepresentation)
  description TEXT NOT NULL,        -- Detailed description of the issue
  status public.dispute_status_enum NOT NULL DEFAULT 'open',

  -- Admin Resolution
  admin_notes TEXT,                 -- Notes from admin during review process
  resolution VARCHAR(50),           -- Resolution outcome (refund, accepted, rejected, replacement)

  -- Audit Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_status CHECK (
    status IN ('open', 'admin_review', 'resolved', 'closed')
  ),
  CONSTRAINT valid_reason CHECK (reason <> ''),
  CONSTRAINT valid_description CHECK (description <> ''),
  CONSTRAINT non_empty_admin_notes CHECK (admin_notes IS NULL OR admin_notes <> ''),
  CONSTRAINT valid_resolution CHECK (
    resolution IS NULL OR resolution IN ('refund', 'accepted', 'rejected', 'replacement')
  )
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.disputes IS 'Dispute records for exchanges. Tracks issues reported and admin resolution workflow.';
COMMENT ON COLUMN public.disputes.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.disputes.exchange_id IS 'UUID FK to exchanges.id (CASCADE DELETE) - the disputed exchange';
COMMENT ON COLUMN public.disputes.reported_by_id IS 'UUID FK to profiles.id - user who reported the dispute';
COMMENT ON COLUMN public.disputes.reason IS 'Dispute category (damage, wrong_item, not_received, misrepresentation)';
COMMENT ON COLUMN public.disputes.description IS 'Detailed description of the issue from reporter';
COMMENT ON COLUMN public.disputes.status IS 'Dispute resolution status (open -> admin_review -> resolved -> closed)';
COMMENT ON COLUMN public.disputes.admin_notes IS 'Notes added by admin during review process';
COMMENT ON COLUMN public.disputes.resolution IS 'Resolution decision (refund, accepted, rejected, replacement)';
COMMENT ON COLUMN public.disputes.created_at IS 'Timestamp when dispute was created';
COMMENT ON COLUMN public.disputes.updated_at IS 'Timestamp when dispute was last updated';

-- ============================================================================
-- INDEXES - Strategic for query performance
-- ============================================================================

-- Exchanges table indexes
-- Fast lookup of exchanges by requester (what they've requested)
CREATE INDEX IF NOT EXISTS idx_exchanges_requester_id ON public.exchanges(requester_id);

-- Fast lookup of exchanges by lister (what they've listed)
CREATE INDEX IF NOT EXISTS idx_exchanges_lister_id ON public.exchanges(lister_id);

-- Fast lookup of exchanges for a specific toy (all requests for this toy)
CREATE INDEX IF NOT EXISTS idx_exchanges_toy_id ON public.exchanges(toy_id);

-- Fast filtering by status (pending requests, active exchanges, etc.)
CREATE INDEX IF NOT EXISTS idx_exchanges_status ON public.exchanges(status);

-- Fast filtering by creation date (recent exchanges, analytics, pagination)
CREATE INDEX IF NOT EXISTS idx_exchanges_created_at ON public.exchanges(created_at DESC);

-- Composite index: requester + status (find user's pending requests)
CREATE INDEX IF NOT EXISTS idx_exchanges_requester_status ON public.exchanges(requester_id, status);

-- Composite index: lister + status (find user's pending listings to accept/reject)
CREATE INDEX IF NOT EXISTS idx_exchanges_lister_status ON public.exchanges(lister_id, status);

-- Delivery confirmations table indexes
-- Fast lookup of delivery confirmation for an exchange
CREATE INDEX IF NOT EXISTS idx_delivery_confirmations_exchange_id ON public.delivery_confirmations(exchange_id);

-- Fast filtering delivery confirmations by condition (analytics, dispute stats)
CREATE INDEX IF NOT EXISTS idx_delivery_confirmations_condition ON public.delivery_confirmations(condition_received);

-- Disputes table indexes
-- Fast lookup of disputes for an exchange
CREATE INDEX IF NOT EXISTS idx_disputes_exchange_id ON public.disputes(exchange_id);

-- Fast lookup of disputes reported by a user
CREATE INDEX IF NOT EXISTS idx_disputes_reported_by_id ON public.disputes(reported_by_id);

-- Fast filtering disputes by status (open disputes need admin attention)
CREATE INDEX IF NOT EXISTS idx_disputes_status ON public.disputes(status);

-- Fast filtering disputes by creation date (recent activity, analytics)
CREATE INDEX IF NOT EXISTS idx_disputes_created_at ON public.disputes(created_at DESC);

-- Composite index: status + created_at (admin dashboard: open disputes, oldest first)
CREATE INDEX IF NOT EXISTS idx_disputes_status_created ON public.disputes(status, created_at);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on all tables (policies will be created separately in rls_policies.sql)
-- RLS ensures users can only see their own exchanges and disputes

-- Enable RLS on exchanges table
ALTER TABLE public.exchanges ENABLE ROW LEVEL SECURITY;

-- Enable RLS on delivery_confirmations table
ALTER TABLE public.delivery_confirmations ENABLE ROW LEVEL SECURITY;

-- Enable RLS on disputes table
ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- 1. Exchange Lifecycle Transitions:
--    pending_request -> accepted -> in_transit -> delivered -> confirmed -> completed
--    Alternative: pending_request -> canceled (at any point)
--    Alternative: accepted -> canceled (both parties agree)
--    Alternative: any state -> auto_completed (48h timeout)
--    Alternative: any state -> disputed (if issues arise)
--
-- 2. Soft Delete Strategy:
--    - Exchanges use status='canceled' for soft delete instead of hard delete
--    - This preserves audit trail for fraud investigation and compliance
--    - All related records (delivery_confirmations, disputes) use CASCADE DELETE
--      so they are physically removed when exchange is deleted
--
-- 3. Immutability of toy_id:
--    - toy_id cannot be updated after exchange creation
--    - This is enforced at the application layer (no UPDATE on this column)
--    - Database enforces at app-level through migration
--
-- 4. Delivery Confirmation:
--    - Each exchange can have at most one delivery confirmation (UNIQUE exchange_id)
--    - Created when requester confirms receipt (status='delivered' -> 'confirmed')
--    - Captures toy condition and proof photos
--
-- 5. Disputes:
--    - Can be created for any exchange after delivery (when delivery_confirmation exists)
--    - Supports multiple dispute types: damage, wrong_item, not_received, misrepresentation
--    - Admin resolution workflow: open -> admin_review -> resolved -> closed
--
-- 6. Indexes Strategy:
--    - requester_id, lister_id, toy_id: FK columns indexed for JOIN performance
--    - status: indexed for soft delete and workflow filtering queries
--    - created_at: indexed for time-based pagination and analytics
--    - Composite indexes for common query patterns (requester+status, lister+status)
--    - All indexes chosen to minimize write overhead while maximizing read speed
--
-- 7. RLS Policies:
--    - Will be created in separate migration: supabase/migrations/*_rls_policies.sql
--    - Policies ensure users can only see/modify their own exchanges
--
-- 8. Constraints:
--    - requester_not_lister: Prevents a user from exchanging with themselves
--    - Valid status, condition, reason values: Enforced via CHECK constraints
--    - Non-empty strings: Enforced via CHECK constraints where required
--    - Photos count >= 0: Enforced for data sanity
