-- Create Messaging & Communication Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0005_create_messaging_tables.sql
-- Description: Creates exchange_messages and blocklist tables with triggers for blocking enforcement
--              and content moderation, including auto-flagging of suspicious messages
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- EXCHANGE_MESSAGES TABLE
-- ============================================================================
-- Stores all messages exchanged between users during an active exchange
-- Implements soft delete via is_deleted_by_sender flag for message persistence
-- Tracks moderation flags for messages containing sensitive information
-- Relationship: Many messages per exchange (one exchange can have multiple messages)

CREATE TABLE IF NOT EXISTS public.exchange_messages (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  exchange_id UUID NOT NULL REFERENCES public.exchanges(id) ON DELETE CASCADE,  -- Exchange this message belongs to
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,     -- User sending the message

  -- Message Content
  content TEXT NOT NULL,  -- Message body (max 500 characters enforced via CHECK constraint)

  -- Moderation & Flags
  moderation_flag BOOLEAN NOT NULL DEFAULT false,  -- True if message needs admin review
  moderation_notes TEXT,                           -- Admin notes about moderation decision
  is_deleted_by_sender BOOLEAN NOT NULL DEFAULT false,  -- Soft delete flag (sender can hide their messages)

  -- Soft Delete Support
  deleted_at TIMESTAMP WITH TIME ZONE,  -- Timestamp when message was deleted (NULL if not deleted)

  -- Audit Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_content_length CHECK (LENGTH(content) > 0 AND LENGTH(content) <= 500),
  CONSTRAINT non_empty_content CHECK (content <> ''),
  CONSTRAINT valid_moderation_notes CHECK (
    moderation_notes IS NULL OR (LENGTH(moderation_notes) > 0 AND LENGTH(moderation_notes) <= 1000)
  ),
  CONSTRAINT deleted_at_consistency CHECK (
    (is_deleted_by_sender = true AND deleted_at IS NOT NULL) OR
    (is_deleted_by_sender = false AND deleted_at IS NULL)
  )
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.exchange_messages IS 'Messages exchanged between users during an active exchange. Implements soft delete via is_deleted_by_sender flag. Auto-flags messages containing phone numbers, addresses, or payment terms.';
COMMENT ON COLUMN public.exchange_messages.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.exchange_messages.exchange_id IS 'UUID FK to exchanges.id - the exchange this message belongs to (CASCADE DELETE)';
COMMENT ON COLUMN public.exchange_messages.sender_id IS 'UUID FK to profiles.id - user who sent this message';
COMMENT ON COLUMN public.exchange_messages.content IS 'Message text (1-500 characters, enforced via CHECK constraint)';
COMMENT ON COLUMN public.exchange_messages.moderation_flag IS 'True if message contains suspicious content (phone, address, payment terms) or was flagged by admin';
COMMENT ON COLUMN public.exchange_messages.moderation_notes IS 'Admin notes about why message was flagged or decision taken (max 1000 chars)';
COMMENT ON COLUMN public.exchange_messages.is_deleted_by_sender IS 'True if sender deleted their message (soft delete, not removed from DB)';
COMMENT ON COLUMN public.exchange_messages.deleted_at IS 'Timestamp when message was deleted by sender (NULL if not deleted)';
COMMENT ON COLUMN public.exchange_messages.created_at IS 'Timestamp when message was sent';

-- ============================================================================
-- BLOCKLIST TABLE
-- ============================================================================
-- Tracks blocked user relationships (blocking is directional: blocker -> blocked)
-- Prevents blocked users from sending messages to each other
-- Unique constraint ensures each blocker can only block each blocked user once

CREATE TABLE IF NOT EXISTS public.blocklist (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  blocker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,  -- User doing the blocking
  blocked_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,  -- User being blocked

  -- Block Reason (optional)
  reason TEXT,  -- Optional reason for the block (e.g., "spam", "inappropriate behavior")

  -- Audit Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT blocker_not_self CHECK (blocker_id != blocked_id),  -- Cannot block oneself
  CONSTRAINT valid_reason CHECK (reason IS NULL OR (LENGTH(reason) > 0 AND LENGTH(reason) <= 500)),
  UNIQUE (blocker_id, blocked_id)  -- Unique constraint: each user can only block another user once
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.blocklist IS 'Directional blocking relationship between users. Prevents blocked users from messaging during exchanges. Unique constraint ensures (blocker_id, blocked_id) is unique.';
COMMENT ON COLUMN public.blocklist.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.blocklist.blocker_id IS 'UUID FK to profiles.id - user initiating the block (CASCADE DELETE)';
COMMENT ON COLUMN public.blocklist.blocked_id IS 'UUID FK to profiles.id - user being blocked (CASCADE DELETE)';
COMMENT ON COLUMN public.blocklist.reason IS 'Optional reason for blocking (max 500 chars)';
COMMENT ON COLUMN public.blocklist.created_at IS 'Timestamp when block was created';

-- ============================================================================
-- TRIGGER FUNCTIONS FOR MESSAGING LOGIC
-- ============================================================================

-- TRIGGER FUNCTION 1: Check if sender is blocked by the other party in the exchange
-- Prevents messages if the recipient has blocked the sender
-- Fired BEFORE INSERT on exchange_messages
CREATE OR REPLACE FUNCTION public.check_message_blocked()
RETURNS TRIGGER AS $$
DECLARE
  v_exchange RECORD;
  v_is_blocked BOOLEAN;
BEGIN
  -- Get exchange details to determine who the recipient is
  SELECT requester_id, lister_id INTO v_exchange
  FROM public.exchanges
  WHERE id = NEW.exchange_id;

  -- Determine recipient: if sender is requester, recipient is lister (and vice versa)
  -- Check if recipient has blocked the sender
  SELECT EXISTS(
    SELECT 1 FROM public.blocklist
    WHERE blocker_id = (
      CASE
        WHEN NEW.sender_id = v_exchange.requester_id THEN v_exchange.lister_id
        ELSE v_exchange.requester_id
      END
    )
    AND blocked_id = NEW.sender_id
  ) INTO v_is_blocked;

  -- Raise exception if sender is blocked by recipient
  IF v_is_blocked THEN
    RAISE EXCEPTION 'Cannot send message: recipient has blocked you';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER FUNCTION 2: Auto-flag messages containing suspicious content
-- Detects phone numbers (7+ digits), address keywords, payment keywords, and sets moderation_flag
-- Also populates moderation_notes with reason for flagging
-- Fired BEFORE INSERT on exchange_messages
CREATE OR REPLACE FUNCTION public.auto_flag_suspicious_messages()
RETURNS TRIGGER AS $$
DECLARE
  v_content_lower TEXT;
  v_has_phone_number BOOLEAN := false;
  v_has_address BOOLEAN := false;
  v_has_payment_terms BOOLEAN := false;
  v_flags_found TEXT[] := ARRAY[]::TEXT[];
BEGIN
  v_content_lower := LOWER(NEW.content);

  -- Check for phone number pattern (7 or more consecutive digits)
  v_has_phone_number := (v_content_lower ~ '\d{7,}');
  IF v_has_phone_number THEN
    v_flags_found := array_append(v_flags_found, 'phone_number');
  END IF;

  -- Check for address keywords (street, avenue, road, etc.)
  v_has_address := (
    v_content_lower ~ '\b(street|avenue|road|lane|drive|boulevard|circle|court|way|place|address|zip|postal|state|city|county)\b'
  );
  IF v_has_address THEN
    v_flags_found := array_append(v_flags_found, 'address_keywords');
  END IF;

  -- Check for payment keywords (venmo, paypal, bank, account, credit card, etc.)
  v_has_payment_terms := (
    v_content_lower ~ '\b(venmo|paypal|bank|account|credit card|debit card|wire transfer|payment|bitcoin|crypto|pay me|cash app|google pay|apple pay)\b'
  );
  IF v_has_payment_terms THEN
    v_flags_found := array_append(v_flags_found, 'payment_keywords');
  END IF;

  -- If any flags were found, set moderation_flag and populate moderation_notes
  IF array_length(v_flags_found, 1) > 0 THEN
    NEW.moderation_flag := true;
    NEW.moderation_notes := 'Auto-flagged by system: ' || array_to_string(v_flags_found, ', ');
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger 1: Check blocking status before allowing message insert
-- Prevents blocked users from communicating during exchanges
CREATE TRIGGER trg_check_message_blocked
BEFORE INSERT ON public.exchange_messages
FOR EACH ROW
EXECUTE FUNCTION public.check_message_blocked();

-- Trigger 2: Auto-flag suspicious messages before insert
-- Detects and flags phone numbers, addresses, and payment terms
CREATE TRIGGER trg_auto_flag_suspicious_messages
BEFORE INSERT ON public.exchange_messages
FOR EACH ROW
EXECUTE FUNCTION public.auto_flag_suspicious_messages();

-- ============================================================================
-- INDEXES - Strategic for query performance
-- ============================================================================

-- Exchange messages table indexes
-- Fast lookup of all messages for a specific exchange (with time ordering)
CREATE INDEX IF NOT EXISTS idx_exchange_messages_exchange_created ON public.exchange_messages(exchange_id, created_at DESC);

-- Fast lookup of messages sent by a specific user (for user activity/audit)
CREATE INDEX IF NOT EXISTS idx_exchange_messages_sender_id ON public.exchange_messages(sender_id);

-- Fast filtering of non-deleted messages (for message list queries)
CREATE INDEX IF NOT EXISTS idx_exchange_messages_deleted_at ON public.exchange_messages(deleted_at);

-- Composite index: exchange + deleted_at (find active messages for an exchange)
CREATE INDEX IF NOT EXISTS idx_exchange_messages_exchange_deleted ON public.exchange_messages(exchange_id, deleted_at);

-- Fast lookup of messages needing moderation review (admin dashboard)
CREATE INDEX IF NOT EXISTS idx_exchange_messages_moderation_flag ON public.exchange_messages(moderation_flag) WHERE moderation_flag = true;

-- Blocklist table indexes
-- Fast lookup of users blocked by a specific blocker
CREATE INDEX IF NOT EXISTS idx_blocklist_blocker_id ON public.blocklist(blocker_id);

-- Fast lookup of users blocking a specific user (reverse relationship)
CREATE INDEX IF NOT EXISTS idx_blocklist_blocked_id ON public.blocklist(blocked_id);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on messaging tables (policies will be created separately in Task 2.9)
-- RLS ensures users can only see messages from their own exchanges and blocklist

-- Enable RLS on exchange_messages table
ALTER TABLE public.exchange_messages ENABLE ROW LEVEL SECURITY;

-- Enable RLS on blocklist table
ALTER TABLE public.blocklist ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- 1. Exchange Messages Lifecycle:
--    - Messages are created when users communicate during an active exchange
--    - Soft delete via is_deleted_by_sender flag (sender can hide their messages)
--    - deleted_at is set to CURRENT_TIMESTAMP when is_deleted_by_sender is true
--    - Messages are never hard-deleted (preserved for auditing and moderation)
--
-- 2. Blocking System:
--    - Directional: blocker_id -> blocked_id (A blocks B does not mean B blocks A)
--    - Prevents blocked users from sending messages during exchanges
--    - UNIQUE (blocker_id, blocked_id) ensures each pair can only block once
--    - blocker_not_self CHECK constraint prevents self-blocking
--
-- 3. Trigger Logic:
--    - check_message_blocked(): Prevents message INSERT if recipient has blocked sender
--      * Determines recipient based on exchange requester/lister roles
--      * Raises exception if blocking relationship found
--      * Fired BEFORE INSERT to fail fast
--
--    - auto_flag_suspicious_messages(): Auto-flags potentially unsafe messages
--      * Detects phone numbers: regex \d{7,} (7+ consecutive digits)
--      * Detects address keywords: street, avenue, road, lane, drive, boulevard, etc.
--      * Detects payment keywords: venmo, paypal, bank, credit card, crypto, etc.
--      * Sets moderation_flag = true and populates moderation_notes with reasons
--      * Multiple triggers can set flags (flags are cumulative)
--
-- 4. Moderation System:
--    - moderation_flag: Indicates message needs admin review
--    - moderation_notes: Contains auto-generated reason or admin decision notes
--    - Flagged messages are visible but marked for review by admin dashboard
--    - Content length constraint (1-500 chars) prevents abuse
--
-- 5. Soft Delete Strategy:
--    - is_deleted_by_sender = true when sender deletes their message
--    - deleted_at is set to CURRENT_TIMESTAMP on deletion
--    - CHECK constraint ensures consistency: deleted_at IS NOT NULL iff is_deleted_by_sender = true
--    - Messages are never hard-deleted (preserved for disputes and audit)
--
-- 6. Indexes Strategy:
--    - (exchange_id, created_at DESC): Fast retrieval of messages for an exchange (sorted by time)
--    - sender_id: Fast lookup of messages sent by a user (audit/user activity)
--    - deleted_at: Fast filtering of non-deleted messages (WHERE deleted_at IS NULL)
--    - (exchange_id, deleted_at): Combined index for "active messages in exchange"
--    - moderation_flag (partial): Only indexes flagged messages (WHERE moderation_flag = true)
--      * Partial indexes reduce size and improve performance for admin dashboard
--    - (blocker_id, blocked_id): Part of UNIQUE constraint; used for block lookups
--    - blocked_id: Used for reverse lookups (who is blocking this user)
--
-- 7. RLS Policies:
--    - Will be created in separate migration: Task 2.9
--    - Policies ensure:
--      * Users can only see messages from exchanges they participate in
--      * Users can only see blocklist entries they created
--      * Admins can see all messages (for moderation)
--
-- 8. Performance Considerations:
--    - Trigger functions use PL/pgSQL for efficiency
--    - check_message_blocked() does single row lookup (no table scans)
--    - auto_flag_suspicious_messages() uses regex pattern matching (can be optimized with trigram indexes if needed)
--    - Indexes on (exchange_id, created_at) optimize message list queries
--    - Partial index on moderation_flag reduces admin dashboard query costs
--
-- 9. Constraints:
--    - valid_content_length: Enforces 1-500 character limit
--    - non_empty_content: Prevents empty strings
--    - valid_moderation_notes: Enforces max 1000 characters
--    - deleted_at_consistency: Ensures is_deleted_by_sender and deleted_at are synchronized
--    - blocker_not_self: Prevents users from blocking themselves
--    - valid_reason: Enforces max 500 characters for block reason
--    - UNIQUE (blocker_id, blocked_id): Ensures no duplicate blocks
--
-- 10. Future Enhancements:
--     - Add message_thread_id for threaded conversations
--     - Add read_at timestamp for message read status
--     - Add attachment_count for message attachments (implemented via separate table)
--     - Add reply_to_message_id for threaded replies
--     - Consider read receipts and typing indicators via Realtime subscriptions
