-- Create Ratings & Reviews Tables Schema for Toy-for-Toy Platform
-- Migration: 20241114_0012_create_ratings_tables.sql
-- Description: Creates ratings, user_stats tables with triggers for automatic stats updates
--              Supports rating of exchanges with condition and communication metrics
-- Author: PostgreSQL Architecture Specialist

-- ============================================================================
-- RATINGS TABLE
-- ============================================================================
-- Stores ratings and reviews for completed exchanges (1:1 with exchanges)
-- Enables users to rate trading partners on communication and toy condition
-- Unique constraint on exchange_id prevents duplicate ratings per exchange

CREATE TABLE IF NOT EXISTS public.ratings (
  -- Primary Key
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  -- Foreign Keys
  exchange_id UUID NOT NULL UNIQUE REFERENCES public.exchanges(id) ON DELETE CASCADE,
  rater_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rated_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,

  -- Rating Metrics (5-point scale)
  condition_rating INT NOT NULL,
  communication_rating INT NOT NULL,

  -- Review Text (max 500 chars, nullable)
  review_text TEXT,

  -- Audit Timestamp
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT rater_not_rated CHECK (rater_id != rated_user_id),
  CONSTRAINT valid_condition_rating CHECK (condition_rating BETWEEN 1 AND 5),
  CONSTRAINT valid_communication_rating CHECK (communication_rating BETWEEN 1 AND 5),
  CONSTRAINT valid_review_length CHECK (review_text IS NULL OR LENGTH(review_text) <= 500)
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.ratings IS 'Ratings and reviews for completed exchanges. Enables users to rate trading partners on toy condition and communication.';
COMMENT ON COLUMN public.ratings.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.ratings.exchange_id IS 'UUID FK to exchanges.id (UNIQUE: one rating per exchange, CASCADE DELETE)';
COMMENT ON COLUMN public.ratings.rater_id IS 'UUID FK to profiles.id - user who created the rating (CASCADE DELETE)';
COMMENT ON COLUMN public.ratings.rated_user_id IS 'UUID FK to profiles.id - user being rated (CASCADE DELETE)';
COMMENT ON COLUMN public.ratings.condition_rating IS 'Toy condition rating (1-5 scale)';
COMMENT ON COLUMN public.ratings.communication_rating IS 'Trading partner communication rating (1-5 scale)';
COMMENT ON COLUMN public.ratings.review_text IS 'Optional review text (max 500 characters)';
COMMENT ON COLUMN public.ratings.created_at IS 'Timestamp when rating was created';

-- ============================================================================
-- USER_STATS TABLE
-- ============================================================================
-- Denormalized statistics for user ratings (computed via triggers)
-- Stores aggregated metrics for efficient dashboard and profile queries
-- Updated automatically whenever a rating is inserted, updated, or deleted

CREATE TABLE IF NOT EXISTS public.user_stats (
  -- Primary Key
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,

  -- Aggregated Metrics
  total_exchanges INT DEFAULT 0 NOT NULL,
  avg_condition_rating NUMERIC(2, 1),
  avg_communication_rating NUMERIC(2, 1),
  avg_overall_rating NUMERIC(2, 1),
  review_count INT DEFAULT 0 NOT NULL,

  -- Audit Timestamp
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_total_exchanges CHECK (total_exchanges >= 0),
  CONSTRAINT valid_review_count CHECK (review_count >= 0),
  CONSTRAINT valid_avg_condition CHECK (avg_condition_rating IS NULL OR (avg_condition_rating >= 1 AND avg_condition_rating <= 5)),
  CONSTRAINT valid_avg_communication CHECK (avg_communication_rating IS NULL OR (avg_communication_rating >= 1 AND avg_communication_rating <= 5)),
  CONSTRAINT valid_avg_overall CHECK (avg_overall_rating IS NULL OR (avg_overall_rating >= 1 AND avg_overall_rating <= 5))
);

-- Add comprehensive comments for documentation
COMMENT ON TABLE public.user_stats IS 'Denormalized user statistics for ratings. Aggregated metrics computed via triggers on ratings table changes.';
COMMENT ON COLUMN public.user_stats.user_id IS 'UUID primary key, references profiles.id (CASCADE DELETE)';
COMMENT ON COLUMN public.user_stats.total_exchanges IS 'Total number of completed exchanges with ratings (denormalized from ratings count)';
COMMENT ON COLUMN public.user_stats.avg_condition_rating IS 'Average toy condition rating across all ratings (NUMERIC(2,1), NULL if no ratings)';
COMMENT ON COLUMN public.user_stats.avg_communication_rating IS 'Average communication rating across all ratings (NUMERIC(2,1), NULL if no ratings)';
COMMENT ON COLUMN public.user_stats.avg_overall_rating IS 'Average of condition + communication ratings (NUMERIC(2,1), NULL if no ratings)';
COMMENT ON COLUMN public.user_stats.review_count IS 'Count of ratings with review text (denormalized for efficient queries)';
COMMENT ON COLUMN public.user_stats.updated_at IS 'Timestamp when stats were last updated (auto-set by trigger)';

-- ============================================================================
-- FUNCTION: Recalculate user statistics from ratings
-- ============================================================================
-- Called by INSERT/UPDATE/DELETE triggers to refresh aggregated metrics
-- Handles NULL values gracefully (COALESCE for aggregates)
-- Creates user_stats row if it doesn't exist (INSERT trigger scenario)

CREATE OR REPLACE FUNCTION public.recalculate_user_stats(p_user_id UUID)
RETURNS void AS $$
DECLARE
  v_total_exchanges INT;
  v_avg_condition NUMERIC(2, 1);
  v_avg_communication NUMERIC(2, 1);
  v_avg_overall NUMERIC(2, 1);
  v_review_count INT;
BEGIN
  -- Calculate aggregates from ratings where rated_user_id = p_user_id
  SELECT
    COUNT(DISTINCT exchange_id)::INT,
    ROUND(COALESCE(AVG(condition_rating), 0)::NUMERIC, 1)::NUMERIC(2, 1),
    ROUND(COALESCE(AVG(communication_rating), 0)::NUMERIC, 1)::NUMERIC(2, 1),
    COUNT(*) FILTER (WHERE review_text IS NOT NULL)::INT
  INTO
    v_total_exchanges,
    v_avg_condition,
    v_avg_communication,
    v_review_count
  FROM public.ratings
  WHERE rated_user_id = p_user_id;

  -- Calculate overall average as average of condition + communication
  IF v_total_exchanges > 0 THEN
    v_avg_overall := ROUND(((v_avg_condition + v_avg_communication) / 2.0)::NUMERIC, 1)::NUMERIC(2, 1);
  ELSE
    v_avg_condition := NULL;
    v_avg_communication := NULL;
    v_avg_overall := NULL;
  END IF;

  -- Insert or update user_stats row
  INSERT INTO public.user_stats (user_id, total_exchanges, avg_condition_rating, avg_communication_rating, avg_overall_rating, review_count, updated_at)
  VALUES (p_user_id, v_total_exchanges, v_avg_condition, v_avg_communication, v_avg_overall, v_review_count, CURRENT_TIMESTAMP)
  ON CONFLICT (user_id) DO UPDATE SET
    total_exchanges = EXCLUDED.total_exchanges,
    avg_condition_rating = EXCLUDED.avg_condition_rating,
    avg_communication_rating = EXCLUDED.avg_communication_rating,
    avg_overall_rating = EXCLUDED.avg_overall_rating,
    review_count = EXCLUDED.review_count,
    updated_at = EXCLUDED.updated_at;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.recalculate_user_stats(UUID) IS 'Recalculates aggregated user statistics from ratings. Called by triggers on INSERT/UPDATE/DELETE.';

-- ============================================================================
-- TRIGGER: Update user stats on rating INSERT
-- ============================================================================
-- Recalculates user_stats whenever a new rating is inserted
-- Handles creation of user_stats row if it doesn't exist

CREATE OR REPLACE FUNCTION public.trigger_update_user_stats_on_rating_insert()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM public.recalculate_user_stats(NEW.rated_user_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_stats_on_rating_insert
AFTER INSERT ON public.ratings
FOR EACH ROW
EXECUTE FUNCTION public.trigger_update_user_stats_on_rating_insert();

COMMENT ON TRIGGER trigger_update_user_stats_on_rating_insert ON public.ratings IS 'Updates user_stats when a rating is inserted';

-- ============================================================================
-- TRIGGER: Update user stats on rating DELETE
-- ============================================================================
-- Recalculates user_stats when a rating is deleted
-- Ensures stats remain consistent after deletion

CREATE OR REPLACE FUNCTION public.trigger_update_user_stats_on_rating_delete()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM public.recalculate_user_stats(OLD.rated_user_id);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_stats_on_rating_delete
AFTER DELETE ON public.ratings
FOR EACH ROW
EXECUTE FUNCTION public.trigger_update_user_stats_on_rating_delete();

COMMENT ON TRIGGER trigger_update_user_stats_on_rating_delete ON public.ratings IS 'Updates user_stats when a rating is deleted';

-- ============================================================================
-- TRIGGER: Update user stats on rating UPDATE
-- ============================================================================
-- Recalculates user_stats when a rating is updated (ratings might be editable)
-- Only recalculates if the rated_user_id changes (unlikely but defensive)

CREATE OR REPLACE FUNCTION public.trigger_update_user_stats_on_rating_update()
RETURNS TRIGGER AS $$
BEGIN
  -- Recalculate for both old and new rated_user_id in case it changed (unlikely)
  IF OLD.rated_user_id != NEW.rated_user_id THEN
    PERFORM public.recalculate_user_stats(OLD.rated_user_id);
  END IF;
  PERFORM public.recalculate_user_stats(NEW.rated_user_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_user_stats_on_rating_update
AFTER UPDATE ON public.ratings
FOR EACH ROW
EXECUTE FUNCTION public.trigger_update_user_stats_on_rating_update();

COMMENT ON TRIGGER trigger_update_user_stats_on_rating_update ON public.ratings IS 'Updates user_stats when a rating is updated';

-- ============================================================================
-- INDEXES - Strategic for query performance
-- ============================================================================

-- Ratings table indexes
-- UNIQUE index on exchange_id (enforces one rating per exchange)
CREATE UNIQUE INDEX IF NOT EXISTS idx_ratings_exchange_id_unique ON public.ratings(exchange_id);

-- Fast lookup of ratings given by a user
CREATE INDEX IF NOT EXISTS idx_ratings_rater_id ON public.ratings(rater_id);

-- Fast lookup of ratings received by a user (for profile/stats queries)
CREATE INDEX IF NOT EXISTS idx_ratings_rated_user_id ON public.ratings(rated_user_id);

-- Fast filtering/sorting by creation date (recent ratings first)
CREATE INDEX IF NOT EXISTS idx_ratings_created_at ON public.ratings(created_at DESC);

-- Composite index: rated_user_id + created_at (common query pattern for user's ratings timeline)
CREATE INDEX IF NOT EXISTS idx_ratings_rated_created ON public.ratings(rated_user_id, created_at DESC);

-- User stats indexes (minimal, since user_id is PK)
-- Index for looking up stats by user_id (already covered by PK, but explicit for clarity)
CREATE INDEX IF NOT EXISTS idx_user_stats_updated_at ON public.user_stats(updated_at DESC);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on both tables (policies will be created in Task 2.9)

ALTER TABLE public.ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_stats ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- NOTES:
-- ============================================================================
-- 1. Ratings Constraints:
--    - rater_id != rated_user_id: Prevents users from rating themselves
--    - condition_rating BETWEEN 1 AND 5: 5-point scale enforced at DB layer
--    - communication_rating BETWEEN 1 AND 5: 5-point scale enforced at DB layer
--    - review_text length <= 500 chars: Application can display feedback on constraint violation
--    - exchange_id UNIQUE: Each exchange can have at most one rating
--
-- 2. User Stats Denormalization:
--    - total_exchanges: Count of distinct exchange_ids for the user
--    - avg_condition_rating: Average condition_rating across all ratings
--    - avg_communication_rating: Average communication_rating across all ratings
--    - avg_overall_rating: Average of (condition_rating + communication_rating) / 2
--    - review_count: Count of ratings where review_text IS NOT NULL
--    - Denormalized for query efficiency on user profiles/dashboards
--
-- 3. Trigger Strategy:
--    - AFTER INSERT: Create/update user_stats for rated_user_id
--    - AFTER DELETE: Recalculate user_stats (avg will drop if rating removed)
--    - AFTER UPDATE: Recalculate user_stats (for edited ratings)
--    - Uses UPSERT logic (INSERT ... ON CONFLICT) to handle missing user_stats rows
--    - NULL handling: Aggregates use COALESCE to handle empty result sets
--
-- 4. Performance Considerations:
--    - Indexes on rater_id and rated_user_id for fast FK lookups
--    - Composite index (rated_user_id, created_at) for "get user's ratings" queries
--    - updated_at index on user_stats for materialization tracking
--    - avg_* columns are NUMERIC(2,1) to store values like 4.5 with 1 decimal place
--
-- 5. Badge Computation:
--    - Badge logic (e.g., "Trusted Trader" if avg_overall_rating >= 4.5) is in API layer
--    - Database only stores raw ratings and computed averages
--    - Keeps database logic simple; business rules in application
--
-- 6. RLS Policies:
--    - Will be created in Task 2.9 (separate migration)
--    - Should prevent users from modifying others' ratings
--    - Should allow public read access to published ratings (user isolation by exchange)
--
-- 7. Testing Strategy:
--    - Test INSERT: Create rating, verify user_stats auto-created and updated
--    - Test DELETE: Delete rating, verify averages recalculated correctly
--    - Test UPDATE: Modify rating, verify stats reflect new values
--    - Test NULL handling: User with no ratings should have NULL avg values
--    - Test constraints: Attempt invalid rating values (0, 6), self-rating, >500 char review
--
-- 8. Data Integrity:
--    - Foreign key CASCADE DELETE on profiles ensures data cleanup on user deletion
--    - CASCADE DELETE on exchanges ensures rating removed if exchange deleted
--    - UNIQUE constraint on exchange_id prevents duplicate ratings
--    - CHECK constraints enforce business logic at database layer
