-- Create Tickets & Wallet System Schema for Toy-for-Toy Platform
-- Migration: 20241114_create_tickets_wallet_system.sql
-- Description: Creates tickets, transaction_log, and game_fragments tables with enums, triggers, constraints, and indexes

-- ============================================================================
-- ENUMS
-- ============================================================================

-- Transaction type enum for audit trail
CREATE TYPE public.transaction_type_enum AS ENUM (
  'issue_starter',      -- Initial starter tickets issued to new users
  'earned_exchange',    -- Tickets earned from completing an exchange (seller)
  'spent_request',      -- Tickets spent when requesting a toy (buyer)
  'refunded',           -- Tickets refunded due to cancelled or failed exchange
  'fragment_redeemed'   -- Tickets earned from redeeming game fragments
);

-- ============================================================================
-- TICKETS TABLE
-- ============================================================================
-- Stores user ticket balances, frozen tickets (in escrow), and game earnings
-- The 'available' column is auto-calculated as (balance - frozen) via trigger
-- This enables efficient queries for available balance without computation

CREATE TABLE IF NOT EXISTS public.tickets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID UNIQUE NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  balance INT DEFAULT 0 NOT NULL,
  frozen INT DEFAULT 0 NOT NULL,
  available INT GENERATED ALWAYS AS (balance - frozen) STORED,
  earned_from_games INT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_balance CHECK (balance >= 0),
  CONSTRAINT valid_frozen CHECK (frozen >= 0),
  CONSTRAINT valid_earned_games CHECK (earned_from_games >= 0)
);

-- Add comments for documentation
COMMENT ON TABLE public.tickets IS 'User ticket balances, frozen amounts, and game earnings';
COMMENT ON COLUMN public.tickets.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.tickets.user_id IS 'UUID foreign key to profiles.id (UNIQUE - one record per user)';
COMMENT ON COLUMN public.tickets.balance IS 'Total tickets owned by user (INT, default: 0)';
COMMENT ON COLUMN public.tickets.frozen IS 'Tickets held in escrow during active exchanges (INT, default: 0)';
COMMENT ON COLUMN public.tickets.available IS 'Computed column: balance - frozen (GENERATED ALWAYS AS STORED)';
COMMENT ON COLUMN public.tickets.earned_from_games IS 'Fragments earned from mini-games (0-4, default: 0)';
COMMENT ON COLUMN public.tickets.created_at IS 'Timestamp when tickets record was created';
COMMENT ON COLUMN public.tickets.updated_at IS 'Timestamp when tickets record was last updated';

-- ============================================================================
-- TRANSACTION_LOG TABLE
-- ============================================================================
-- Append-only audit trail for all ticket movements
-- Provides complete history for accountability and fraud detection
-- DELETE operations are prevented via RLS policies

CREATE TABLE IF NOT EXISTS public.transaction_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type public.transaction_type_enum NOT NULL,
  amount INT NOT NULL,
  related_exchange_id UUID,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add comments for documentation
COMMENT ON TABLE public.transaction_log IS 'Append-only audit trail for all ticket transactions';
COMMENT ON COLUMN public.transaction_log.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.transaction_log.user_id IS 'UUID foreign key to profiles.id';
COMMENT ON COLUMN public.transaction_log.type IS 'Transaction type ENUM (issue_starter, earned_exchange, spent_request, refunded, fragment_redeemed)';
COMMENT ON COLUMN public.transaction_log.amount IS 'Ticket or fragment amount (INT)';
COMMENT ON COLUMN public.transaction_log.related_exchange_id IS 'Optional UUID linking to exchanges table for context';
COMMENT ON COLUMN public.transaction_log.notes IS 'Optional TEXT field for additional context or metadata';
COMMENT ON COLUMN public.transaction_log.created_at IS 'Timestamp when transaction was recorded (automatically set)';

-- ============================================================================
-- GAME_FRAGMENTS TABLE
-- ============================================================================
-- Stores fragment earnings from mini-games per kid
-- Fragments are accumulated and converted to tickets (4 fragments = 1 ticket)
-- Uses NUMERIC(2,2) to store 0.25, 0.5, 0.75, 1.0 values with precision

CREATE TABLE IF NOT EXISTS public.game_fragments (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  kid_id UUID NOT NULL REFERENCES public.kids(id) ON DELETE CASCADE,
  game_id VARCHAR(50) NOT NULL,
  fragments_earned NUMERIC(3, 2) NOT NULL,
  bonus_earned NUMERIC(3, 2) DEFAULT 0,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  -- Constraints
  CONSTRAINT valid_fragments CHECK (fragments_earned > 0),
  CONSTRAINT valid_bonus CHECK (bonus_earned >= 0)
);

-- Add comments for documentation
COMMENT ON TABLE public.game_fragments IS 'Game fragment earnings per kid from mini-games (4 fragments = 1 ticket)';
COMMENT ON COLUMN public.game_fragments.id IS 'UUID primary key generated by uuid_generate_v4()';
COMMENT ON COLUMN public.game_fragments.kid_id IS 'UUID foreign key to kids.id';
COMMENT ON COLUMN public.game_fragments.game_id IS 'VARCHAR game identifier (e.g., color-match, puzzle-game)';
COMMENT ON COLUMN public.game_fragments.fragments_earned IS 'NUMERIC(3,2) fragments earned from game play (0.25, 0.5, 0.75, 1.0)';
COMMENT ON COLUMN public.game_fragments.bonus_earned IS 'NUMERIC(3,2) bonus fragments from ads or achievements (default: 0)';
COMMENT ON COLUMN public.game_fragments.timestamp IS 'Timestamp when fragments were earned';

-- ============================================================================
-- TRIGGER: Update 'available' column in tickets table
-- ============================================================================
-- Automatically updates the available column whenever balance or frozen changes
-- This ensures available = balance - frozen is always in sync
-- Implemented as BEFORE UPDATE trigger to validate and compute before storing

CREATE OR REPLACE FUNCTION public.update_tickets_available()
RETURNS TRIGGER AS $$
BEGIN
  -- The 'available' column is GENERATED ALWAYS AS (balance - frozen) STORED
  -- PostgreSQL automatically computes this, so no manual update needed
  -- This trigger ensures updated_at is set on every update
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_tickets_available_trigger
BEFORE UPDATE ON public.tickets
FOR EACH ROW
EXECUTE FUNCTION public.update_tickets_available();

COMMENT ON FUNCTION public.update_tickets_available() IS 'Trigger function to update updated_at timestamp and validate available calculation on tickets changes';
COMMENT ON TRIGGER update_tickets_available_trigger ON public.tickets IS 'Ensures updated_at is set whenever balance or frozen changes';

-- ============================================================================
-- INDEXES
-- ============================================================================
-- Strategic indexes for common query patterns and performance optimization

-- Index on tickets.user_id for fast lookups by user
CREATE INDEX IF NOT EXISTS idx_tickets_user_id ON public.tickets(user_id);

-- Index on transaction_log.user_id for efficient transaction history queries
CREATE INDEX IF NOT EXISTS idx_transaction_log_user_id ON public.transaction_log(user_id);

-- Index on transaction_log.created_at for time-based queries and sorting
CREATE INDEX IF NOT EXISTS idx_transaction_log_created_at ON public.transaction_log(created_at);

-- Composite index on transaction_log(user_id, created_at) for common query pattern
CREATE INDEX IF NOT EXISTS idx_transaction_log_user_created ON public.transaction_log(user_id, created_at DESC);

-- Index on game_fragments.kid_id for efficient fragment lookups by kid
CREATE INDEX IF NOT EXISTS idx_game_fragments_kid_id ON public.game_fragments(kid_id);

-- Index on game_fragments.timestamp for time-based queries
CREATE INDEX IF NOT EXISTS idx_game_fragments_timestamp ON public.game_fragments(timestamp DESC);

-- Index on game_fragments.game_id for game-specific queries
CREATE INDEX IF NOT EXISTS idx_game_fragments_game_id ON public.game_fragments(game_id);

-- ============================================================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================================================
-- Enable RLS on all three tables
-- Specific policies will be created in a separate RLS policies migration

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_fragments ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Notes:
-- ============================================================================
-- 1. RLS policies are NOT created in this migration. They will be added separately in:
--    supabase/migrations/rls_policies.sql
--
-- 2. The 'available' column in tickets is a GENERATED ALWAYS AS (STORED) column.
--    PostgreSQL automatically maintains this computed column.
--    The trigger only handles updated_at timestamp updates.
--
-- 3. Transaction log is designed to be append-only:
--    - INSERT: Allowed (audit trail creation)
--    - UPDATE: Allowed (for correcting notes, but not amount/type)
--    - DELETE: Should be prevented via RLS policies (no delete permission)
--
-- 4. Fragment precision: NUMERIC(3,2) allows values 0.00-9.99 with 2 decimal places
--    Examples: 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, etc.
--    This supports the 4-fragments = 1-ticket conversion (0.25 per game × 4 = 1.0)
--
-- 5. Indexes are strategic for common query patterns:
--    - idx_tickets_user_id: Support "get ticket balance by user"
--    - idx_transaction_log_user_id: Support "get transaction history"
--    - idx_transaction_log_created_at: Support time-based sorting and range queries
--    - idx_game_fragments_kid_id: Support "get game earnings by kid"
--    - idx_game_fragments_timestamp: Support "recent games first" queries
--    - Composite indexes optimize common WHERE + ORDER BY patterns
--
-- 6. Constraints enforce business logic:
--    - balance >= 0: Prevent negative balances
--    - frozen >= 0: Prevent negative frozen amounts
--    - earned_from_games >= 0: Prevent negative game earnings
--    - fragments_earned > 0: Ensure positive game fragment contributions
--    - bonus_earned >= 0: Allow zero or positive bonuses
--
-- 7. Foreign keys with ON DELETE CASCADE ensure:
--    - When a profile is deleted, all tickets/transactions/fragments are deleted
--    - When a kid is deleted, all fragments for that kid are deleted
--    - Maintains referential integrity automatically
